/**
 * 자동 생성 — PDS/scripts/generate-pds-tokens.mjs. 직접 고치지 마세요.
 * 정본: packages/pds-react/tokens.css (사람이 관리한다)
 *
 * 값을 여기 적는 게 아니라 CSS 변수를 가리킨다. 두 번째 인자는 폴백 —
 * 토큰 CSS 가 없는 환경에서만 쓰이며, 정본의 alias 를 끝까지 따라가
 * 얻은 값이라 어긋나지 않는다.
 */

const v = (name: string, fallback: string) => `var(${name}, ${fallback})`;

export const color = {
  "accentNeutral": v('--color-accent-neutral', "#60a5fa"),
  "accentNormal": v('--color-accent-normal', "#1d7ff9"),
  "accentStrong": v('--color-accent-strong', "#1458ad"),
  "actionNormal": v('--color-action-normal', "#000000"),
  "actionStrong": v('--color-action-strong', "#454c53"),
  "aiHover": v('--color-ai-hover', "#f5f1fd"),
  "aiNormal": v('--color-ai-normal', "#6f3ad0"),
  "aiPressed": v('--color-ai-pressed', "#e0d1ff"),
  "aiStrong": v('--color-ai-strong', "#511bb2"),
  "backgroundBase": v('--color-background-base', "#ffffff"),
  "fillNeutral": v('--color-fill-neutral', "#f7f8f9"),
  "fillNormal": v('--color-fill-normal', "#f2f4f6"),
  "fillStrong": v('--color-fill-strong', "#e8ebed"),
  "formatImage": v('--color-format-image', "#00badb"),
  "formatImageHover": v('--color-format-image-hover', "#d2f4fa"),
  "formatImageHoverAdaptive": v('--color-format-image-hover-adaptive', "#d2f4fa"),
  "formatImagePressed": v('--color-format-image-pressed', "#abebf6"),
  "formatImagePressedAdaptive": v('--color-format-image-pressed-adaptive', "#abebf6"),
  "formatNote": v('--color-format-note', "#f2b50b"),
  "formatNoteHover": v('--color-format-note-hover', "#fcefca"),
  "formatNoteHoverAdaptive": v('--color-format-note-hover-adaptive', "#fcefca"),
  "formatNotePressed": v('--color-format-note-pressed', "#fae6af"),
  "formatNotePressedAdaptive": v('--color-format-note-pressed-adaptive', "#fae6af"),
  "formatPdf": v('--color-format-pdf', "#f95c5c"),
  "formatPdfHover": v('--color-format-pdf-hover', "#ffe3e3"),
  "formatPdfHoverAdaptive": v('--color-format-pdf-hover-adaptive', "#ffe3e3"),
  "formatPdfPressed": v('--color-format-pdf-pressed', "#fdcece"),
  "formatPdfPressedAdaptive": v('--color-format-pdf-pressed-adaptive', "#fdcece"),
  "formatSheet": v('--color-format-sheet', "#51b41b"),
  "formatSheetHover": v('--color-format-sheet-hover', "#dcf1d1"),
  "formatSheetHoverAdaptive": v('--color-format-sheet-hover-adaptive', "#dcf1d1"),
  "formatSheetPressed": v('--color-format-sheet-pressed', "#cae8ba"),
  "formatSheetPressedAdaptive": v('--color-format-sheet-pressed-adaptive', "#cae8ba"),
  "formatSlide": v('--color-format-slide', "#fd8900"),
  "formatSlideHover": v('--color-format-slide-hover', "#fde5c8"),
  "formatSlideHoverAdaptive": v('--color-format-slide-hover-adaptive', "#fde5c8"),
  "formatSlidePressed": v('--color-format-slide-pressed', "#fedbb2"),
  "formatSlidePressedAdaptive": v('--color-format-slide-pressed-adaptive', "#fedbb2"),
  "formatWord": v('--color-format-word', "#1d7ff9"),
  "formatWordHover": v('--color-format-word-hover', "#d9eaff"),
  "formatWordHoverAdaptive": v('--color-format-word-hover-adaptive', "#d9eaff"),
  "formatWordPressed": v('--color-format-word-pressed', "#bbd8fd"),
  "formatWordPressedAdaptive": v('--color-format-word-pressed-adaptive', "#bbd8fd"),
  "interactionHover": v('--color-interaction-hover', "#f2f4f6"),
  "interactionPressed": v('--color-interaction-pressed', "#e8ebed"),
  "labelAlternative": v('--color-label-alternative', "#72787f"),
  "labelAssistive": v('--color-label-assistive', "#9ea4aa"),
  "labelInverse": v('--color-label-inverse', "#ffffff"),
  "labelNeutral": v('--color-label-neutral', "#454c53"),
  "labelNormal": v('--color-label-normal', "#26282b"),
  "layerOverlay": v('--color-layer-overlay', "#00000080"),
  "layerSurface": v('--color-layer-surface', "#ffffff"),
  "lineNeutral": v('--color-line-neutral', "#e8ebed"),
  "lineNormal": v('--color-line-normal', "#c9cdd2"),
  "lineStrong": v('--color-line-strong', "#b3b8bd"),
  "linkNormal": v('--color-link-normal', "#1d7ff9"),
  "linkStrong": v('--color-link-strong', "#1458ad"),
  "linkVisited": v('--color-link-visited', "#404dc2"),
  "planAi": v('--color-plan-ai', "#6f3ad0"),
  "planAiBg": v('--color-plan-ai-bg', "#7736d81a"),
  "planBasic": v('--color-plan-basic', "#449916"),
  "planBasicBg": v('--color-plan-basic-bg', "#009b001a"),
  "planBusiness": v('--color-plan-business', "#2baff4"),
  "planBusinessBg": v('--color-plan-business-bg', "#00b2fa1a"),
  "planOrange": v('--color-plan-orange', "#d77400"),
  "planOrangeBg": v('--color-plan-orange-bg', "#e66d001a"),
  "planPro": v('--color-plan-pro', "#0046b9"),
  "planProBg": v('--color-plan-pro-bg', "#0047c01a"),
  "planSmart": v('--color-plan-smart', "#1d7ff9"),
  "planSmartBg": v('--color-plan-smart-bg', "#0081ff1a"),
  "stateError": v('--color-state-error', "#f95c5c"),
  "stateNew": v('--color-state-new', "#fb4949"),
  "staticBlack": v('--color-static-black', "#000000"),
  "staticWhite": v('--color-static-white', "#ffffff"),
} as const;

export const duration = {
  "fast": v('--duration-fast', "150ms"),
  "instant": v('--duration-instant', "100ms"),
  "normal": v('--duration-normal', "250ms"),
  "slow": v('--duration-slow', "350ms"),
} as const;

export const ease = {
  "in": v('--ease-in', "cubic-bezier(0.4, 0, 1, 1)"),
  "inOut": v('--ease-in-out', "cubic-bezier(0.4, 0, 0.2, 1)"),
  "out": v('--ease-out', "cubic-bezier(0, 0, 0.2, 1)"),
} as const;

export const radius = {
  "2xl": v('--radius-2xl', "38px"),
  "3xl": v('--radius-3xl', "64px"),
  "full": v('--radius-full', "999px"),
  "lg": v('--radius-lg', "16px"),
  "md": v('--radius-md', "12px"),
  "none": v('--radius-none', "0px"),
  "sm": v('--radius-sm', "8px"),
  "xl": v('--radius-xl', "24px"),
  "xs": v('--radius-xs', "6px"),
  "xxs": v('--radius-xxs', "4px"),
} as const;

export const shadow = {
  "lg": v('--shadow-lg', "0 4px 16px rgba(0, 0, 0, 0.08)"),
  "md": v('--shadow-md', "0 2px 12px rgba(0, 0, 0, 0.06)"),
  "sm": v('--shadow-sm', "0 1px 8px rgba(0, 0, 0, 0.04)"),
  "xl": v('--shadow-xl', "0 6px 24px rgba(0, 0, 0, 0.12)"),
} as const;

export const spacing = {
  "2xl": v('--spacing-2xl', "40px"),
  "2xs": v('--spacing-2xs', "8px"),
  "3xl": v('--spacing-3xl', "48px"),
  "3xs": v('--spacing-3xs', "4px"),
  "4xl": v('--spacing-4xl', "64px"),
  "4xs": v('--spacing-4xs', "2px"),
  "lg": v('--spacing-lg', "24px"),
  "md": v('--spacing-md', "20px"),
  "none": v('--spacing-none', "0px"),
  "sm": v('--spacing-sm', "16px"),
  "xl": v('--spacing-xl', "32px"),
  "xs": v('--spacing-xs', "12px"),
} as const;

export const typography = {
  "body1FontFamily": v('--typography-body1-font-family', "Pretendard"),
  "body1FontSize": v('--typography-body1-font-size', "16px"),
  "body1LineHeight": v('--typography-body1-line-height', "1.5"),
  "body2FontFamily": v('--typography-body2-font-family', "Pretendard"),
  "body2FontSize": v('--typography-body2-font-size', "14px"),
  "body2LineHeight": v('--typography-body2-line-height', "1.5"),
  "body3FontFamily": v('--typography-body3-font-family', "Pretendard"),
  "body3FontSize": v('--typography-body3-font-size', "13px"),
  "body3LineHeight": v('--typography-body3-line-height', "1.5"),
  "caption1FontFamily": v('--typography-caption1-font-family', "Pretendard"),
  "caption1FontSize": v('--typography-caption1-font-size', "12px"),
  "caption1LineHeight": v('--typography-caption1-line-height', "1.3"),
  "caption2FontFamily": v('--typography-caption2-font-family', "Pretendard"),
  "caption2FontSize": v('--typography-caption2-font-size', "11px"),
  "caption2LineHeight": v('--typography-caption2-line-height', "1.3"),
  "displayFontFamily": v('--typography-display-font-family', "Pretendard"),
  "displayFontSize": v('--typography-display-font-size', "40px"),
  "displayLineHeight": v('--typography-display-line-height', "1.4"),
  "heading1FontFamily": v('--typography-heading1-font-family', "Pretendard"),
  "heading1FontSize": v('--typography-heading1-font-size', "28px"),
  "heading1LineHeight": v('--typography-heading1-line-height', "1.4"),
  "heading2FontFamily": v('--typography-heading2-font-family', "Pretendard"),
  "heading2FontSize": v('--typography-heading2-font-size', "24px"),
  "heading2LineHeight": v('--typography-heading2-line-height', "1.4"),
  "heading3FontFamily": v('--typography-heading3-font-family', "Pretendard"),
  "heading3FontSize": v('--typography-heading3-font-size', "20px"),
  "heading3LineHeight": v('--typography-heading3-line-height', "1.4"),
  "heading4FontFamily": v('--typography-heading4-font-family', "Pretendard"),
  "heading4FontSize": v('--typography-heading4-font-size', "18px"),
  "heading4LineHeight": v('--typography-heading4-line-height', "1.4"),
  "labelButtonFontFamily": v('--typography-label-button-font-family', "Pretendard"),
  "labelButtonFontSize": v('--typography-label-button-font-size', "16px"),
  "labelButtonFontWeight": v('--typography-label-button-font-weight', "700"),
  "labelButtonLineHeight": v('--typography-label-button-line-height', "1.4"),
  "labelButtonSmFontFamily": v('--typography-label-button-sm-font-family', "Pretendard"),
  "labelButtonSmFontSize": v('--typography-label-button-sm-font-size', "14px"),
  "labelButtonSmFontWeight": v('--typography-label-button-sm-font-weight', "500"),
  "labelButtonSmLineHeight": v('--typography-label-button-sm-line-height', "1.4"),
  "titleFontFamily": v('--typography-title-font-family', "Pretendard"),
  "titleFontSize": v('--typography-title-font-size', "32px"),
  "titleLineHeight": v('--typography-title-line-height', "1.4"),
} as const;
