// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designSecurityPatterns.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 보안 패턴 상수 — 무의존 단일 소스 (스킬·플러그인·디자인 3계 공용).
 *
 * 원위치(skillValidation=INJECTION_PATTERNS · pluginOverlay=SECRET_SCAN_PATTERNS ·
 * skillRefConstants=SANDBOX_FENCE_MARKER)에서 re-home — 기존 위치는 re-export 하위호환이라
 * 소비처는 무수정. design/ 폴더에 둔 이유: 스탠드얼론 킷(PDS) 생성이 이 폴더
 * 복사만으로 완결되게 하기 위함 (pluginOverlay 경유 시 getSupabaseServer·RAW_PLUGIN_FILES
 * 가 전이 의존으로 딸려와 킷이 컴파일 불가).
 *
 * Node 의존(path/Buffer/crypto) 없음 — 클라이언트 번들 안전 (skillRefConstants 와 동일 규율).
 */

/** 프롬프트 인젝션 차단 패턴 — 스킬 산문(설명·본문)과 디자인 산문 계층 공용. */
export const INJECTION_PATTERNS = [
  /<file_operation>/i,
  /ignore\s+(previous|all)\s+(instructions?|prompts?)/i,
  /system\s*prompt/i,
  /api_call/i,
  /allowed.?tools/i,
];

/**
 * 공개 repo 커밋 전 시크릿 스캔용 **고신뢰** 패턴.
 * ⚠️ `sanitize.ts` 의 `sanitizeFileSnippet`(lossy 마스커, `sk-`/`key-`/RFC1918 IP 광역 매칭)를
 * 재사용하면 "key-value", "task-based", "192.168.x" 같은 **정상 문서**를 오탐 reject 한다.
 * SKILL.md·DESIGN.md 본문은 문서 산문이라 오탐 비용이 크므로, 여기선 접두어·서명 길이로
 * 고신뢰 시크릿만 잡는다.
 */
export const SECRET_SCAN_PATTERNS: readonly RegExp[] = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,                                   // 사설 키 블록
  /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{8,}/,      // JWT(3-part+서명) — supabase service_role/anon
  /sk-ant-[A-Za-z0-9_-]{16,}/,                                            // Anthropic
  /sk-proj-[A-Za-z0-9_-]{16,}/,                                           // OpenAI project
  /sk-[A-Za-z0-9]{20,}/,                                                  // 고전 OpenAI(20+ alnum — "sk-based" 등 산문 회피)
  /sk_live_[A-Za-z0-9]{16,}/,                                             // Stripe live
  /sk_test_[A-Za-z0-9]{16,}/,                                             // Stripe test
  /gh[pousr]_[A-Za-z0-9]{36}/,                                            // GitHub 토큰 5종
  /github_pat_[A-Za-z0-9_]{40,}/,                                         // GitHub fine-grained PAT
  /sbp_[A-Za-z0-9_-]{20,}/,                                               // Supabase PAT
  /sb_secret_[A-Za-z0-9_-]{16,}/,                                         // Supabase 신형 secret key
  /AKIA[0-9A-Z]{16}/,                                                     // AWS access key
  /AIza[0-9A-Za-z_-]{35}/,                                                // Google API key
  /xox[baprs]-[A-Za-z0-9-]{10,}/,                                         // Slack
  /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/,                             // SendGrid
  /vc_[A-Za-z0-9]{24,}/,                                                  // Vercel
  /\b(?:postgres(?:ql)?|mongodb(?:\+srv)?|mysql|redis|amqps?):\/\/[^\s/@:]+:[^\s/@]+@/i, // 자격증명 포함 DB URL
  /(?:service_role_key|supabase_service_role_key)\s*[:=]/i,               // service_role 대입문
];

/**
 * 사용자 정의 스킬 샌드박스 펜스 마커 접두사 — [chat/route.ts sandboxSkillContent] 와 단일 소스.
 * 참조/본문/디자인 content 가 이 문자열을 포함하면 펜스 위조(탈옥) 시도로 간주해 거부한다.
 */
export const SANDBOX_FENCE_MARKER = '[사용자 정의 스킬 지침';
