// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designCompat.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 외부 DESIGN.md 호환 정규화 — 업로드 파이프라인 전단.
 *
 * getdesign.md(awesome-design-md) 등 외부 생태계의 DESIGN.md 를 **원본 그대로 업로드**해도
 * 동작하도록, 파싱 전에 우리 프로토콜로 결정적 변환한다. 파서(designParser)의 엄격함은
 * 그대로 유지 — 이 계층이 흡수하는 것은 실측(stripe·vercel·claude 원본)으로 확인된 차이다:
 *
 *   1. name 이 kebab-case 가 아님        → kebab 정규화 (+원문은 title 로 보존)
 *   2. version 이 semver 가 아님(alpha)  → 1.0.0 폴백
 *   3. tokens: 없이 최상위 카테고리 직접  → 단일 tokens: 블록으로 이동 (+키 kebab 화)
 *   4. 교차참조 값 `{colors.primary}`    → 스칼라 참조는 실제 값으로 치환(스펙 기능),
 *      맵 참조·미해결 참조가 남는 카테고리(components 스펙 등)는 토큰이 아니라
 *      **참조 문서(YAML)** 로 보존 — 데이터 소실 없음
 *   5. 컴포넌트 H3 에 코드 펜스 없음      → 참조 문서(Resources)로 이동 (스펙 산문 보존)
 *
 * 정규형(canonical — 인용 스칼라) 파일엔 바이트 no-op — 멱등성 테스트로 잠금.
 * 우리 스펙의 비인용 스칼라 등은 **의미 보존 재직렬화**(인용 통일·빈 줄 정리)가 일어나며
 * 이는 구조 변환이 아니라 notes[] 를 발행하지 않는다(tokens 의미 동일).
 * 구조 변환(카테고리 이동·리소스 강등 등)은 전부 notes[] 로 업로드 응답에 투명 보고된다.
 * 보안 게이트(designValidation)는 정규화 **이후** 동일하게 적용 — 우회 없음.
 */

import { DESIGN_NAME_RE, DESIGN_VERSION_RE, DESIGN_TITLE_MAX } from './designConstants';
import { slugifyTitle } from './designParser';

export interface CompatResult {
  content: string;
  notes: string[];
}

const FENCE_OPEN_RE = /^```[a-zA-Z0-9-]*[ \t]*$/;
const FENCE_CLOSE_RE = /^```[ \t]*$/;
const TOP_KEY_RE = /^([A-Za-z0-9_-]+):[ \t]*(.*)$/;
const CHILD_KEY_RE = /^([ \t]+)([A-Za-z0-9_-]+):[ \t]*(.*)$/;
const REF_RE = /\{([A-Za-z0-9_.-]+)\}/g;

/** 예약 최상위 필드 — 토큰 카테고리로 취급하지 않음 */
const RESERVED = new Set(['name', 'title', 'version', 'description', 'stack', 'tokens', 'themes']);
/** 카테고리 이름 표준화 (가이드 비주얼 섹션과 정합) */
const CATEGORY_ALIAS: Record<string, string> = {
  colors: 'color',
  shadows: 'shadow',
  radii: 'radius',
  rounded: 'radius',
};

const toKebab = (s: string): string =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');

const stripOuterQuotes = (v: string): string => {
  const t = v.trim();
  if (t.length >= 2) {
    const a = t[0];
    const b = t[t.length - 1];
    if ((a === '"' && b === '"') || (a === "'" && b === "'")) return t.slice(1, -1);
  }
  return t;
};

/* ── frontmatter 텍스트 → 최상위 블록 ── */

interface TopBlock {
  key: string;
  scalar: string;
  children: string[];
}

function splitTopBlocks(fmLines: string[]): TopBlock[] {
  const blocks: TopBlock[] = [];
  let cur: TopBlock | null = null;
  for (const ln of fmLines) {
    if (!ln.trim() || ln.trim().startsWith('#')) continue;
    const top = !/^[ \t]/.test(ln) ? ln.match(TOP_KEY_RE) : null;
    if (top) {
      cur = { key: top[1], scalar: top[2].trim(), children: [] };
      blocks.push(cur);
      continue;
    }
    if (cur) cur.children.push(ln);
  }
  return blocks;
}

/* ── 카테고리 자식 라인 → 트리 (교차참조 해석·재직렬화용 구조 파스) ── */

interface TokenNode {
  value?: string;
  children?: Map<string, TokenNode>;
}

function parseChildren(lines: string[]): Map<string, TokenNode> {
  const root = new Map<string, TokenNode>();
  const stack: Array<{ indent: number; map: Map<string, TokenNode> }> = [{ indent: 0, map: root }];
  for (const ln of lines) {
    const m = ln.match(CHILD_KEY_RE);
    if (!m) continue; // 시퀀스·비정형 라인 — 파서가 최종 판정(여기선 스킵)
    const indent = m[1].replace(/\t/g, '  ').length;
    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) stack.pop();
    const parent = stack[stack.length - 1].map;
    const key = m[2];
    const rest = m[3].trim();
    if (rest === '') {
      const child: TokenNode = { children: new Map() };
      parent.set(key, child);
      stack.push({ indent, map: child.children! });
    } else {
      parent.set(key, { value: stripOuterQuotes(rest) });
    }
  }
  return root;
}

function serializeTree(map: Map<string, TokenNode>, indent: string, kebabKeys: boolean): string[] {
  const out: string[] = [];
  for (const [key, node] of map) {
    const k = kebabKeys ? toKebab(key) || key : key;
    if (node.children) {
      out.push(`${indent}${k}:`);
      out.push(...serializeTree(node.children, indent + '  ', kebabKeys));
    } else {
      out.push(`${indent}${k}: ${JSON.stringify(node.value ?? '')}`);
    }
  }
  return out;
}

/** 토큰이 아니라 컴포넌트 스펙으로 다뤄야 하는 최상위 카테고리 이름 */
const SPEC_BLOCK_CATS = new Set(['components', 'component']);

export function normalizeExternalDesignMd(raw: string): CompatResult {
  const notes: string[] = [];
  const lines = raw.split(/\r\n|\r|\n/);
  if (lines[0]?.trim() !== '---') return { content: raw, notes };

  let fmEnd = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') {
      fmEnd = i;
      break;
    }
  }
  if (fmEnd === -1) return { content: raw, notes };

  const fmLines = lines.slice(1, fmEnd);
  const bodyLines = lines.slice(fmEnd + 1);

  /* ── 1) frontmatter 스칼라 필드 ── */
  const blocks = splitTopBlocks(fmLines);
  const get = (key: string) => blocks.find((b) => b.key === key);

  const rawName = stripOuterQuotes(get('name')?.scalar ?? '');
  let name = rawName;
  let title = stripOuterQuotes(get('title')?.scalar ?? '').replace(/"/g, '');
  if (rawName && !DESIGN_NAME_RE.test(rawName)) {
    name = slugifyTitle(rawName) || 'imported-design';
    if (!title) title = rawName.replace(/"/g, '').slice(0, DESIGN_TITLE_MAX);
    notes.push(`이름 "${rawName.slice(0, 40)}" → "${name}" 으로 정규화했어요.`);
  }

  let version = stripOuterQuotes(get('version')?.scalar ?? '');
  if (version && !DESIGN_VERSION_RE.test(version)) {
    notes.push(`버전 "${version.slice(0, 20)}" 은 semver 형식이 아니라 1.0.0 으로 등록했어요.`);
    version = '1.0.0';
  }

  let description = get('description')?.scalar ?? '';
  // 블록 스칼라 설명(`description: |` — nike/raycast/posthog 실측) → 한 줄로 합침
  const descBlock = get('description');
  if (descBlock && /^[|>]-?$/.test(descBlock.scalar) && descBlock.children.length > 0) {
    description = descBlock.children.map((l) => l.trim()).join(' ');
    notes.push('여러 줄 설명(블록 스칼라)을 한 줄로 합쳤어요.');
  }
  if (stripOuterQuotes(description).length > 1000) {
    description = stripOuterQuotes(description).slice(0, 1000);
    notes.push('설명이 길어 1,000자에서 잘랐어요.');
  }
  const stack = get('stack')?.scalar ?? '';

  /* ── 2) 토큰 카테고리 수집 + 교차참조 해석 ── */
  // 카테고리 트리: 기존 tokens 자식 + 예약 외 최상위 맵 블록
  const categories = new Map<string, { sourceName: string; tree: Map<string, TokenNode> }>();
  const tokensBlock = get('tokens');
  if (tokensBlock) {
    for (const [cat, node] of parseChildren(tokensBlock.children)) {
      if (node.children) categories.set(cat, { sourceName: cat, tree: node.children });
    }
  }
  const movedCategories: string[] = [];
  for (const b of blocks) {
    if (RESERVED.has(b.key)) continue;
    if (b.scalar !== '' || b.children.length === 0) continue;
    const cat = CATEGORY_ALIAS[b.key] ?? (toKebab(b.key) || b.key);
    movedCategories.push(b.key);
    categories.set(cat, { sourceName: b.key, tree: parseChildren(b.children) });
  }
  if (movedCategories.length > 0) {
    notes.push(
      `최상위 카테고리 ${movedCategories.length}개(${movedCategories.slice(0, 5).join(', ')}${movedCategories.length > 5 ? ' 외' : ''})를 tokens 아래로 옮겼어요.`,
    );
  }

  // 참조 인덱스: `{colors.primary}` → 스칼라 값 / 맵 참조는 MAP 마커
  const MAP_REF = Symbol('map');
  const refIndex = new Map<string, string | typeof MAP_REF>();
  const register = (path: string, v: string | typeof MAP_REF) => {
    if (!refIndex.has(path)) refIndex.set(path, v);
  };
  const indexTree = (prefixes: string[], map: Map<string, TokenNode>) => {
    for (const [key, node] of map) {
      const keys = [key, toKebab(key) || key];
      for (const p of prefixes) {
        for (const k of new Set(keys)) {
          if (node.children) {
            register(`${p}.${k}`, MAP_REF);
            indexTree([`${p}.${k}`], node.children);
          } else {
            register(`${p}.${k}`, node.value ?? '');
          }
        }
      }
    }
  };
  for (const [cat, { sourceName, tree }] of categories) {
    indexTree([...new Set([cat, sourceName])], tree);
  }

  // 스칼라 참조 치환 (최대 4패스 — 참조의 참조 허용, 순환은 미해결로 남아 스펙 강등)
  /*
   * 치환 전 원본 스냅샷 — 스펙 블록(components 등)으로 강등될 카테고리는 참조를 **보존**해야 한다.
   * 토큰 참조를 값으로 평탄화해 넘기면 생성기가 그 값과 같은 다른 토큰을 역으로 찾아 쓰게 되고
   * ({color.static-white} → #ffffff → var(--color-background-base)), 다크 테마에서 무너진다.
   */
  const preResolveYaml = new Map<string, string[]>();
  for (const [cat, { tree }] of categories) preResolveYaml.set(cat, serializeTree(tree, '', false));

  let resolvedCount = 0;
  for (let pass = 0; pass < 4; pass++) {
    let changed = false;
    for (const { tree } of categories.values()) {
      const walk = (map: Map<string, TokenNode>) => {
        for (const node of map.values()) {
          if (node.children) {
            walk(node.children);
            continue;
          }
          if (!node.value || !node.value.includes('{')) continue;
          const next = node.value.replace(REF_RE, (whole, path: string) => {
            const hit = refIndex.get(path);
            if (typeof hit === 'string' && !hit.includes('{')) {
              resolvedCount += 1;
              return hit;
            }
            return whole;
          });
          if (next !== node.value) {
            node.value = next;
            changed = true;
          }
        }
      };
      walk(tree);
    }
    if (!changed) break;
  }
  if (resolvedCount > 0) notes.push(`교차참조 ${resolvedCount}개를 실제 값으로 치환했어요.`);

  // 맵 참조·미해결 참조가 남은 카테고리 → 토큰이 아니라 참조 문서(YAML)로 강등
  const hasUnresolved = (map: Map<string, TokenNode>): boolean => {
    for (const node of map.values()) {
      if (node.children) {
        if (hasUnresolved(node.children)) return true;
      } else if (node.value?.includes('{')) {
        return true;
      }
    }
    return false;
  };
  const tokenCats: string[] = [];
  const specCats: Array<{ cat: string; yaml: string[] }> = [];
  for (const [cat, { tree }] of categories) {
    /*
     * `components` 는 예약 이름 — 언제나 컴포넌트 스펙 블록이다.
     * 미해결 참조 유무로만 갈랐더니, 참조가 전부 풀리는 파일에서는 스펙 맵이 토큰으로 편입돼
     * `--components-button-primary-background-color` 같은 변수가 생기고 컴포넌트는 0개가 됐다.
     * (참조가 남는 파일만 우연히 정상 동작했다.)
     */
    if (SPEC_BLOCK_CATS.has(cat) || hasUnresolved(tree)) {
      specCats.push({ cat, yaml: preResolveYaml.get(cat) ?? serializeTree(tree, '', false) });
    } else {
      tokenCats.push(cat);
    }
  }
  if (specCats.length > 0) {
    notes.push(
      `토큰으로 표현할 수 없는 스펙 블록 ${specCats.length}개(${specCats.map((s) => s.cat).join(', ')})는 참조 문서로 등록했어요.`,
    );
  }

  /* ── 3) frontmatter 재조립 ── */
  const outFm: string[] = [];
  if (name) outFm.push(`name: ${name}`);
  if (title) outFm.push(`title: ${title.slice(0, DESIGN_TITLE_MAX)}`);
  if (version) outFm.push(`version: ${version}`);
  if (description) outFm.push(`description: ${description}`);
  if (stack) outFm.push(`stack: ${stack}`);
  if (tokenCats.length > 0) {
    outFm.push('tokens:');
    for (const cat of tokenCats) {
      outFm.push(`  ${cat}:`);
      outFm.push(...serializeTree(categories.get(cat)!.tree, '    ', true));
    }
  }
  const themes = get('themes');
  if (themes) {
    outFm.push('themes:');
    outFm.push(...serializeTree(parseChildren(themes.children), '  ', true));
  }

  /* ── 4) 본문 정규화 — 코드 펜스 없는 컴포넌트 H3 → Resources (펜스-인지) ── */
  interface H3Block {
    heading: string;
    lines: string[];
    hasCodeHeading: boolean;
  }
  const before: string[] = [];
  const after: string[] = [];
  const resourcesTail: string[] = [];
  const componentBlocks: H3Block[] = [];
  let movedIntroProse = false;

  type Phase = 'before' | 'components' | 'resources' | 'after';
  let phase: Phase = 'before';
  let inFence = false;
  let curBlock: H3Block | null = null;
  let componentsSeen = false;
  let resourcesSeen = false;

  const pushLine = (ln: string) => {
    if (phase === 'components') {
      if (curBlock) {
        curBlock.lines.push(ln);
      } else {
        before.push(ln); // 섹션 서두 산문 — 개요로 보존 (파서는 H3 밖 산문 거절)
        if (ln.trim()) movedIntroProse = true;
      }
      return;
    }
    if (phase === 'resources') resourcesTail.push(ln);
    else if (phase === 'after') after.push(ln);
    else before.push(ln);
  };

  for (const ln of bodyLines) {
    if (inFence) {
      pushLine(ln);
      if (FENCE_CLOSE_RE.test(ln)) inFence = false;
      continue;
    }
    if (FENCE_OPEN_RE.test(ln)) {
      inFence = true;
      pushLine(ln);
      continue;
    }
    const h2 = !/^###/.test(ln) ? ln.match(/^##\s+(.+?)\s*$/) : null;
    if (h2) {
      const t = h2[1].toLowerCase();
      if (t === 'components' && !componentsSeen) {
        componentsSeen = true;
        phase = 'components';
        curBlock = null;
        continue;
      }
      if (t === 'resources' && !resourcesSeen) {
        resourcesSeen = true;
        phase = 'resources';
        continue;
      }
      phase = componentsSeen || resourcesSeen ? 'after' : 'before';
      pushLine(ln);
      continue;
    }
    if (phase === 'components') {
      if (/^###\s+/.test(ln) && !/^####/.test(ln)) {
        curBlock = { heading: ln, lines: [], hasCodeHeading: false };
        componentBlocks.push(curBlock);
        continue;
      }
      if (curBlock && /^####\s+code\s*$/i.test(ln)) curBlock.hasCodeHeading = true;
      pushLine(ln);
      continue;
    }
    pushLine(ln);
  }

  const kept = componentBlocks.filter(
    (b) => b.hasCodeHeading && b.lines.some((l) => /^```(tsx|jsx)[ \t]*$/.test(l)),
  );
  // 강등 문서 마커 — 가이드 IA 가 "컴포넌트 문서"를 순수 리소스와 구분해 컴포넌트 그룹에
  // 배치하는 신호 (DesignGuideView 의 COMPONENT_DOC_MARKER 리터럴과 쌍 — 동시 수정 필수).
  // HTML 주석이라 react-markdown(raw HTML 미렌더)·스킬 zip 어디서도 표시되지 않는다.
  const COMPONENT_DOC_MARKER = '<!-- design-md: component-doc -->';
  const demoted = componentBlocks.filter((b) => !kept.includes(b));
  if (demoted.length > 0) {
    notes.push(
      `구현 코드가 없는 컴포넌트 ${demoted.length}개(${demoted
        .slice(0, 4)
        .map((b) => b.heading.replace(/^###\s+/, ''))
        .join(', ')}${demoted.length > 4 ? ' 외' : ''})는 참조 문서로 등록했어요 — 코드를 추가하면 컴포넌트로 올라갑니다.`,
    );
  }
  if (movedIntroProse) notes.push('Components 섹션 서두의 산문은 개요로 옮겼어요.');

  const outBody: string[] = [...before];
  if (kept.length > 0) {
    outBody.push('## Components');
    for (const b of kept) outBody.push(b.heading, ...b.lines);
  }
  if (resourcesSeen || demoted.length > 0 || specCats.length > 0) {
    outBody.push('## Resources');
    outBody.push(...resourcesTail);
    for (const b of demoted) outBody.push(b.heading, COMPONENT_DOC_MARKER, ...b.lines);
    for (const s of specCats) {
      outBody.push(`### Spec ${s.cat}`, '', '```yaml', ...s.yaml, '```', '');
    }
  }
  outBody.push(...after);

  return {
    content: '---\n' + outFm.join('\n') + '\n---\n' + outBody.join('\n'),
    notes,
  };
}
