// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designValidation.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 디자인 시스템 3계층 검증 — 업로드 게이트 (검출 시 전부 **거절**, 마스킹 없음).
 *
 * 1) 산문 계층 (overview/description/usage/variants/리소스 산문):
 *    INJECTION_PATTERNS + 펜스 위조 + chat-template 토큰 거절.
 * 2) 코드 계층 (컴포넌트 code + 리소스 본문 내 코드 펜스):
 *    INJECTION_PATTERNS **미적용**(정상 코드 오탐 — 예: 주석의 "api_call").
 *    대신 SECRET_SCAN + 펜스 위조 + chat-template 토큰 거절.
 *    ⚠️ bare `system:` 은 코드 주석·데모 문자열 오탐이 커서 양 계층 모두 미검사
 *    (의미 있는 케이스는 INJECTION 의 `system prompt` 가 커버).
 * 3) frontmatter 스칼라 계층: 토큰 키/값이 CSS 변수·마크다운 표로 보간되므로
 *    형식 화이트리스트 강제 (design-tokens.css 셀렉터 탈출·표 구조 파괴 차단).
 *
 * 시크릿 스캔은 raw 전문에도 적용(산문 붙여넣기 시크릿 거절) —
 * pluginOverlay.validateOverlayForPublicCommit 의 전문 스캔 선례.
 * ⚠️ sanitize.ts 의 SECRET_REGEXES 는 lossy 마스킹용 광역 매칭이라
 * 거절 게이트에 사용 금지(정상 산문 오탐 — pluginOverlay.ts 주석 참조).
 */

import { INJECTION_PATTERNS, SECRET_SCAN_PATTERNS, SANDBOX_FENCE_MARKER } from './designSecurityPatterns';
import {
  DESIGN_RAW_MAX_BYTES,
  DESIGN_CODE_MAX_BYTES,
  DESIGN_USAGE_MAX_BYTES,
  DESIGN_RESOURCE_MAX_BYTES,
  DESIGN_OVERVIEW_MAX_BYTES,
  DESIGN_TOKENS_MAX_BYTES,
  DESIGN_ITEMS_MAX,
  DESIGN_COMPONENTS_MAX,
  DESIGN_DESCRIPTION_MAX,
  DESIGN_ITEM_DESCRIPTION_MAX,
  DESIGN_TOKEN_KEY_RE,
  DESIGN_TOKEN_VALUE_MAX,
  DESIGN_TOKEN_VALUE_RE,
} from './designConstants';
import { splitFences, type ParsedDesignSystem, type ParseIssue, type DesignTokenMap } from './designParser';

/**
 * 펜스 위조 통합 패턴 — 실제 런타임 펜스 두 계열을 모두 커버:
 * `<untrusted-content ...>` (ssrfGuard.wrapUntrusted, 하이픈) 와
 * `<untrusted_design_component_...>` (wrapDesignPayload, 언더스코어).
 */
const UNTRUSTED_FENCE_RE = /<untrusted[-_]/i;

/** chat-template 역할 토큰 — tsx/jsx 정당 용례 사실상 0 이라 거절 비용 근사 0 */
const CHAT_TEMPLATE_TOKENS = ['<|im_start|>', '<|im_end|>', '[INST]', '[/INST]'] as const;

const encoder = new TextEncoder();
const byteLen = (s: string): number => encoder.encode(s).length;

export interface DesignValidationResult {
  ok: boolean;
  issues: ParseIssue[];
}

function checkFenceForgery(text: string, layer: 'prose' | 'code', path: string, issues: ParseIssue[]): void {
  const nfc = text.normalize('NFC');
  if (nfc.includes(SANDBOX_FENCE_MARKER)) {
    issues.push({ layer, path, message: '스킬 샌드박스 마커 문자열을 포함할 수 없습니다(펜스 위조).' });
  }
  if (UNTRUSTED_FENCE_RE.test(nfc)) {
    issues.push({ layer, path, message: 'untrusted 펜스 태그 문자열을 포함할 수 없습니다(펜스 위조).' });
  }
  for (const token of CHAT_TEMPLATE_TOKENS) {
    if (nfc.includes(token)) {
      issues.push({ layer, path, message: `채팅 템플릿 토큰(${token})을 포함할 수 없습니다.` });
      break;
    }
  }
}

function checkProse(text: string, path: string, issues: ParseIssue[]): void {
  if (!text) return;
  for (const re of INJECTION_PATTERNS) {
    if (re.test(text)) {
      issues.push({ layer: 'prose', path, message: `허용되지 않는 패턴이 있습니다: ${re.source}` });
    }
  }
  checkFenceForgery(text, 'prose', path, issues);
}

function checkCode(text: string, path: string, issues: ParseIssue[]): void {
  if (!text) return;
  checkFenceForgery(text, 'code', path, issues);
  for (const re of SECRET_SCAN_PATTERNS) {
    if (re.test(text)) {
      issues.push({ layer: 'code', path, message: '시크릿으로 보이는 값이 있습니다 — 제거 후 다시 업로드하세요(마스킹하지 않고 거절합니다).' });
      break;
    }
  }
}

/** 산문+코드가 섞인 md(usage/variants/리소스 본문·overview) — 펜스 분리 후 계층별 검사 */
function checkMixedMd(md: string, path: string, issues: ParseIssue[]): void {
  if (!md) return;
  const { prose, fenced } = splitFences(md);
  checkProse(prose, path, issues);
  for (const block of fenced) checkCode(block, path, issues);
}

function checkByteCap(text: string, cap: number, label: string, path: string, issues: ParseIssue[]): void {
  if (byteLen(text) > cap) {
    issues.push({ layer: 'structure', path, message: `${label} 이(가) ${Math.floor(cap / 1024)}KB 를 초과합니다.` });
  }
}

function checkTokenMap(map: DesignTokenMap, fieldPath: string, issues: ParseIssue[]): void {
  for (const [category, entries] of Object.entries(map)) {
    if (!DESIGN_TOKEN_KEY_RE.test(category)) {
      issues.push({ layer: 'structure', path: `${fieldPath}.${category}`, message: '카테고리 이름은 소문자·숫자·하이픈만 가능합니다.' });
    }
    for (const [key, value] of Object.entries(entries)) {
      const path = `${fieldPath}.${category}.${key}`;
      if (!DESIGN_TOKEN_KEY_RE.test(key)) {
        issues.push({ layer: 'structure', path, message: '토큰 키는 소문자·숫자·하이픈만 가능합니다(CSS 변수명으로 사용됩니다).' });
      }
      if (value.length > DESIGN_TOKEN_VALUE_MAX) {
        issues.push({ layer: 'structure', path, message: `토큰 값은 ${DESIGN_TOKEN_VALUE_MAX}자 이하여야 합니다.` });
      } else if (value !== '' && !DESIGN_TOKEN_VALUE_RE.test(value)) {
        issues.push({
          layer: 'structure',
          path,
          message: '토큰 값에 허용되지 않는 문자가 있습니다(세미콜론·중괄호·제어문자 금지 — CSS 값으로 보간됩니다).',
        });
      } else if (/url\s*\(|image-set\s*\(|element\s*\(|\/\//i.test(value)) {
        // 화이트리스트 문자만으로도 조립 가능한 외부 로드 구문 차단 — 가이드 인라인 style ·
        // 생성 design-tokens.css 를 통한 외부 리소스 로드(추적 픽셀 등) 방지. `//` 는
        // 프로토콜 상대 URL(폰트 스택·크기 shorthand 의 단일 `/` 는 영향 없음).
        issues.push({
          layer: 'structure',
          path,
          message: '토큰 값에 외부 로드 구문(url(·image-set(·`//`)은 쓸 수 없습니다.',
        });
      }
    }
  }
}

/**
 * 파싱 결과 + 원문에 대한 3계층 검증. 이슈가 1건이라도 있으면 업로드 거절.
 */
export function validateDesignSystem(parsed: ParsedDesignSystem, raw: string): DesignValidationResult {
  const issues: ParseIssue[] = [];

  // --- 전문 캡·시크릿 (고신뢰 패턴 — 산문 위치 포함 전문 거절) ---
  checkByteCap(raw, DESIGN_RAW_MAX_BYTES, '원문', 'raw', issues);
  for (const re of SECRET_SCAN_PATTERNS) {
    if (re.test(raw)) {
      issues.push({ layer: 'code', path: 'raw', message: '시크릿으로 보이는 값이 있습니다 — 제거 후 다시 업로드하세요.' });
      break;
    }
  }

  // --- frontmatter 스칼라 계층 ---
  if (parsed.description.length > DESIGN_DESCRIPTION_MAX) {
    issues.push({ layer: 'structure', path: 'frontmatter.description', message: `description 은 ${DESIGN_DESCRIPTION_MAX}자 이하여야 합니다.` });
  }
  checkProse(parsed.description, 'frontmatter.description', issues);
  checkProse(parsed.title, 'frontmatter.title', issues);
  checkTokenMap(parsed.tokens, 'frontmatter.tokens', issues);
  for (const [themeName, themeMap] of Object.entries(parsed.themes)) {
    checkTokenMap(themeMap, `frontmatter.themes.${themeName}`, issues);
  }
  checkByteCap(JSON.stringify(parsed.tokens), DESIGN_TOKENS_MAX_BYTES, 'tokens', 'frontmatter.tokens', issues);
  checkByteCap(JSON.stringify(parsed.themes), DESIGN_TOKENS_MAX_BYTES, 'themes', 'frontmatter.themes', issues);

  // --- 개수 캡 (앱 레이어 — DB CHECK 불가 항목) ---
  const itemCount = parsed.components.length + parsed.resources.length;
  if (itemCount > DESIGN_ITEMS_MAX) {
    issues.push({ layer: 'structure', path: 'body', message: `아이템(컴포넌트+리소스)은 최대 ${DESIGN_ITEMS_MAX}개입니다.` });
  }
  if (parsed.components.length > DESIGN_COMPONENTS_MAX) {
    issues.push({ layer: 'structure', path: 'components', message: `컴포넌트는 최대 ${DESIGN_COMPONENTS_MAX}개입니다.` });
  }

  // --- overview ---
  checkByteCap(parsed.overviewMd, DESIGN_OVERVIEW_MAX_BYTES, 'overview', 'overview', issues);
  checkMixedMd(parsed.overviewMd, 'overview', issues);

  // --- 컴포넌트 ---
  for (const c of parsed.components) {
    const path = `components/${c.name}`;
    if (c.description.length > DESIGN_ITEM_DESCRIPTION_MAX) {
      issues.push({ layer: 'structure', path, message: `설명은 ${DESIGN_ITEM_DESCRIPTION_MAX}자 이하여야 합니다.` });
    }
    checkProse(c.title, path, issues); // 헤딩 텍스트도 도구 페이로드·가이드에 보간 — 게이트 우회 차단
    checkMixedMd(c.description, path, issues); // 설명엔 코드 펜스 허용(파서) — 산문/코드 분리 검사
    checkByteCap(c.usageMd, DESIGN_USAGE_MAX_BYTES, 'Usage', path, issues);
    checkByteCap(c.variantsMd, DESIGN_USAGE_MAX_BYTES, 'Variants', path, issues);
    checkMixedMd(c.usageMd, path, issues);
    checkMixedMd(c.variantsMd, path, issues);
    checkByteCap(c.code, DESIGN_CODE_MAX_BYTES, '코드', path, issues);
    checkCode(c.code, path, issues);
  }

  // --- 리소스 ---
  for (const r of parsed.resources) {
    const path = `resources/${r.name}`;
    checkProse(r.title, path, issues);
    checkByteCap(r.bodyMd, DESIGN_RESOURCE_MAX_BYTES, '본문', path, issues);
    checkMixedMd(r.bodyMd, path, issues);
  }

  return { ok: issues.length === 0, issues };
}
