// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designComponentGen.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 브랜드 컴포넌트 스펙 → React 컴포넌트 코드 **결정적 생성** (AI 미사용).
 *
 * 공식 design.md 스펙 파일(frontmatter `components:` 맵)은 완성 코드가 없어
 * 업로드해도 "컴포넌트 0" 이 된다. 스펙이 담는 건 구조화된 스타일 값 집합
 * (backgroundColor·textColor·typography·rounded·padding·height)이므로, 마크업
 * 골격만 우리가 고정하면 **값 주입만으로 진짜 tsx 를 기계 생성**할 수 있다.
 *
 * 원칙:
 * - 결정적: 같은 스펙 → 같은 코드 (AI·네트워크·키 불필요, 실패 경로 없음)
 * - 마크업은 아키타입 템플릿 고정 — 스펙에 없는 구조를 추측하지 않는다
 *   (스타일 입은 단일 요소 + children 이 기본, 상태 있는 컨트롤만 controlled props)
 * - 토큰 우선: 리터럴 값이 토큰 맵에 실존하면 `var(--…)` 로 역매핑해 리브랜딩이
 *   재생성 없이 반영되게 한다. typography 참조는 평탄화 키로 펼친다
 *   (`{typography.label-button}` → font-size/-weight/… 개별 var — 축약 `font:` 는
 *   우리 토큰 모델에 실존하지 않아 스타일이 통째로 무효가 된다)
 * - 관리자 작성 코드 우선: `#### Code` 로 등록된 동명 컴포넌트가 있으면 생성 skip
 * - 순수 코어: 상대 import 만 (킷 COPIES 대상)
 */

import { type ParsedDesignSystem, type DesignTokenMap } from './designParser';
import { GENERATED_CODE_MARK } from './designConstants';

/* ── 타입 ── */

export interface SpecEntry {
  name: string;
  props: Record<string, string>;
}

/**
 * 생성 컴포넌트 식별 마커 — usage_md 에 항상 포함된다.
 * 동일 내용 재업로드(no-op) 경로가 "생성분만" 골라 교체할 때의 조회 축
 * (관리자 작성 컴포넌트·리소스는 건드리지 않는다).
 */
export const GENERATED_MARK = '자동 생성된 컴포넌트입니다 (AI 미사용 · 결정적 변환)';

export interface GeneratedComponent {
  name: string;
  title: string;
  description: string;
  code: string;
  usageMd: string;
  /** 이 컴포넌트를 만든 스펙 엔트리 이름들 (provenance) */
  sourceEntries: string[];
}

/** 상태 변형 접미 — base 스펙을 상속하고 자기 값만 오버라이드하는 엔트리 */
export const SPEC_STATE_SUFFIX_RE = /-(hover|active|pressed|focus|disabled|selected)$/;

/* ── 스펙 파싱 (가이드 뷰의 parseComponentSpecs 와 동형 규약) ── */

/**
 * `### Spec components` 리소스의 yaml 펜스 → 엔트리 목록.
 * 보존 형식: 엔트리 0-들여쓰기 + prop 2칸. 래퍼(`components:`)가 있으면 한 단계씩
 * 밀리므로 상대 들여쓰기로 판정한다.
 */
export function parseComponentSpecs(bodyMd: string): SpecEntry[] {
  const m = bodyMd.match(/```ya?ml\n([\s\S]*?)```/);
  if (!m) return [];
  const out: SpecEntry[] = [];
  let cur: SpecEntry | null = null;
  let entryIndent: number | null = null;
  for (const raw of m[1].split('\n')) {
    const line = raw.replace(/\t/g, '  ');
    const em = line.match(/^(\s*)([\w-]+):\s*$/);
    const pm = line.match(/^(\s*)([\w-]+):\s*(.+?)\s*$/);
    if (em) {
      const indent = em[1].length;
      if (entryIndent === null || indent <= entryIndent) {
        entryIndent = indent;
        cur = { name: em[2], props: {} };
        out.push(cur);
      } else if (cur && Object.keys(cur.props).length === 0) {
        out.pop();
        entryIndent = indent;
        cur = { name: em[2], props: {} };
        out.push(cur);
      }
      continue;
    }
    if (pm && cur && pm[1].length > (entryIndent ?? 0)) {
      cur.props[pm[2]] = pm[3].replace(/^["']|["']$/g, '');
    }
  }
  return out.filter((e) => Object.keys(e.props).length > 0);
}

/** 스펙 이름 → 아키타입 (컨트롤류를 button/input 보다 먼저 — radio-button 오분류 방지) */
export type Archetype =
  | 'button' | 'input' | 'badge' | 'nav' | 'card' | 'band'
  | 'toggle' | 'checkbox' | 'radio' | 'tab' | 'segment' | 'cell' | 'other';

/** icon-button → IconButton */
function toPascalName(base: string): string {
  return base.split('-').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('');
}
/** icon-button → Icon Button */
function toTitleName(base: string): string {
  return base.split('-').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
}

/** 아키타입 판정 규칙 — 위에서부터 처음 걸리는 것. 매칭된 위치가 base 이름의 끝이 된다. */
const ARCHETYPE_RULES: Array<[Archetype, RegExp]> = [
  ['toggle', /toggle|switch/],
  ['checkbox', /checkbox/],
  ['radio', /radio(?!us)/],
  ['segment', /segment/],
  ['tab', /tab(?!le)/],
  ['button', /button|btn|cta(?!-band)/],
  ['input', /input|field|search/],
  ['badge', /badge|pill|tag|chip/],
  // 달력 날짜·아바타·색 견본처럼 한 변이 같은 작은 셀
  // 숫자 접미사(avatar56)도 경계로 인정 — 사이즈가 붙은 이름이 흔하다
  ['cell', /(^|-)(cell|day|avatar|swatch|dot)(?=-|\d|$)/],
  // table-header·grid-header 는 표의 일부다 — 상단 내비로 잡으면 표가 통째로 쪼개진다
  ['nav', /nav|menu-bar|(?<!table-)(?<!grid-)header/],
  // 같은 이유로 table-row·grid-row 는 카드가 아니다 (list-row 는 목록 항목이라 카드가 맞다)
  ['card', /card|tile|listing|(?<!table-)(?<!grid-)row/],
  ['band', /hero|band|footer|banner/],
];

export function specArchetype(name: string): Archetype {
  return ARCHETYPE_RULES.find(([, re]) => re.test(name))?.[0] ?? 'other';
}

/**
 * 컴포넌트 base 이름 — 아키타입을 판정한 **키워드까지**를 잘라낸다.
 * 같은 아키타입이라도 서로 다른 컴포넌트를 구분하기 위한 것:
 *   button-primary48 → button       (키워드가 맨 앞)
 *   icon-button40    → icon-button  (앞에 수식어가 붙은 별개 컴포넌트)
 *   avatar56         → avatar
 *   status-dot-online→ status-dot
 * 키워드를 못 찾으면(=other) 사이즈·상태 접미사만 떼고 그대로 쓴다.
 */
export function specBaseName(name: string): string {
  const stripped = name.replace(SPEC_STATE_SUFFIX_RE, '').replace(/(\d{2,3})$/, '').replace(/-+$/, '');
  const rule = ARCHETYPE_RULES.find(([, re]) => re.test(name));
  if (!rule) return stripped || name;
  const m = stripped.match(rule[1]);
  if (!m || m.index === undefined) return stripped || name;
  // 매칭 끝까지 자르되 경계의 하이픈은 정리 (cell 규칙은 앞뒤 하이픈을 포함해 매칭한다)
  const cut = stripped.slice(0, m.index + m[0].length).replace(/-+$/, '');
  return cut || stripped || name;
}

/* ── 값 → 토큰 var 역매핑 ── */

const CATEGORY_ALIAS: Record<string, string> = {
  colors: 'color',
  color: 'color',
  rounded: 'radius',
  radius: 'radius',
  typography: 'typography',
  spacing: 'spacing',
  shadow: 'shadow',
};

const normalizeValue = (v: string): string => {
  const t = v.trim();
  // #AABBCC ↔ #aabbcc 동일 취급, #ABC → #aabbcc 확장
  const hex = t.match(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
  if (!hex) return t.toLowerCase();
  const h = hex[1];
  return `#${(h.length === 3 ? h.split('').map((c) => c + c).join('') : h).toLowerCase()}`;
};

/**
 * 토큰 맵 → (정규화 값 → CSS 변수명). 같은 값이 여러 키에 있으면 카테고리·키 정렬 첫
 * 항목이 이긴다(결정성). typography 는 스칼라 값이 폰트 크기 등 범용이라 제외 —
 * 색·라운드·간격만 역매핑 대상.
 */
function buildValueToVar(tokens: DesignTokenMap): Map<string, string> {
  const map = new Map<string, string>();
  for (const cat of Object.keys(tokens).sort()) {
    if (cat === 'typography') continue;
    for (const key of Object.keys(tokens[cat]).sort()) {
      const v = normalizeValue(tokens[cat][key]);
      if (!map.has(v)) map.set(v, `--${cat}-${key}`);
    }
  }
  return map;
}

/** 스펙 값 → CSS 값 문자열. `{cat.key}` 참조와 리터럴 모두 토큰 var 로 정렬 */
function toCssValue(
  raw: string | undefined,
  tokens: DesignTokenMap,
  v2v: Map<string, string>,
  allowCats?: string[],
): string | null {
  if (!raw) return null;
  const t = raw.trim();
  if (!t) return null;
  const ref = t.match(/^\{([\w-]+)\.([\w.-]+)\}$/);
  if (ref) {
    const cat = CATEGORY_ALIAS[ref[1]] ?? ref[1];
    const key = ref[2].replace(/\./g, '-');
    // 참조가 실존 토큰일 때만 var — 없으면 원문(미해결 참조는 스타일 무효라 제외)
    return tokens[cat]?.[key] !== undefined ? `var(--${cat}-${key})` : null;
  }
  // 안전 게이트: CSS 값에 허용되지 않는 문자·외부 로드 구문 거절
  if (!/^[a-zA-Z0-9\s#%.,()'"/_-]{1,128}$/.test(t) || /url\s*\(|expression\s*\(|javascript:|\/\//i.test(t)) return null;
  const mapped = v2v.get(normalizeValue(t));
  if (!mapped) return t;
  // 값이 같아도 축이 다른 토큰이면 쓰지 않는다 — 의미가 어긋나면 리터럴이 낫다
  if (allowCats && !allowCats.some((c) => mapped.startsWith(`--${c}-`))) return t;
  return `var(${mapped})`;
}

/** typography 참조 → 평탄화 키 기반 개별 CSS 속성 (축약 font: 금지) */
const TYPO_PROPS: Array<[string, string]> = [
  ['font-size', 'fontSize'],
  ['font-weight', 'fontWeight'],
  ['line-height', 'lineHeight'],
  ['letter-spacing', 'letterSpacing'],
  ['font-family', 'fontFamily'],
];

function typographyStyle(raw: string | undefined, tokens: DesignTokenMap): Array<[string, string]> {
  if (!raw) return [];
  const m = raw.trim().match(/^\{typography\.([\w.-]+)\}$/);
  if (!m) return [];
  const role = m[1].replace(/\./g, '-');
  const out: Array<[string, string]> = [];
  for (const [suffix, cssProp] of TYPO_PROPS) {
    if (tokens.typography?.[`${role}-${suffix}`] !== undefined) {
      out.push([cssProp, `var(--typography-${role}-${suffix})`]);
    }
  }
  return out;
}

/** 스펙 prop → CSS 속성 매핑 (형태에 직접 기여하는 것만) */
/**
 * 리터럴 값을 토큰으로 되돌릴 때 찾아볼 카테고리.
 * 제한하지 않으면 height:64px 이 radius-3xl(같은 64px)로 매칭돼, 라운드 토큰을 조정하면
 * 버튼 높이가 따라 변하는 엉뚱한 결합이 생긴다. 없으면 리터럴로 두는 편이 안전하다.
 */
const REVERSE_LOOKUP_CATS: Record<string, string[]> = {
  backgroundColor: ['color', 'primitive'],
  textColor: ['color', 'primitive'],
  borderColor: ['color', 'primitive'],
  rounded: ['radius'],
  radius: ['radius'],
  padding: ['spacing'],
  height: ['spacing', 'size'],
  width: ['spacing', 'size'],
  size: ['spacing', 'size'],
};

export const SPEC_STYLE_PROPS: Array<[string, string]> = [
  ['backgroundColor', 'backgroundColor'],
  ['textColor', 'color'],
  ['borderColor', 'borderColor'],
  ['rounded', 'borderRadius'],
  ['radius', 'borderRadius'],
  ['padding', 'padding'],
  ['height', 'height'],
  ['width', 'width'],
];

function specToStyle(
  e: SpecEntry | undefined,
  tokens: DesignTokenMap,
  v2v: Map<string, string>,
  skip: Set<string> = new Set(),
): Array<[string, string]> {
  if (!e) return [];
  const out: Array<[string, string]> = [];
  for (const [prop, css] of SPEC_STYLE_PROPS) {
    if (skip.has(css)) continue;
    const v = toCssValue(e.props[prop], tokens, v2v, REVERSE_LOOKUP_CATS[prop]);
    if (v !== null) out.push([css, v]);
  }
  if (!skip.has('font')) out.push(...typographyStyle(e.props.typography, tokens));
  if (e.props.borderColor && !skip.has('borderStyle')) out.push(['borderStyle', 'solid'], ['borderWidth', '1px']);
  return out;
}

/* ── 그룹핑 (엔트리 이름 파싱 — 결정적) ── */

export interface VariantGroup {
  key: string;
  base?: SpecEntry;
  states: Record<string, SpecEntry>;
}

export interface ArchGroup {
  arch: Archetype;
  variants: VariantGroup[];
  sizes: Array<[string, SpecEntry]>;
  entries: SpecEntry[];
  /**
   * 변형에 속하지 않는 컴포넌트 전역 상태(`button-disabled` 처럼 변형 이름 없이 상태만 있는 엔트리).
   * 예전에는 base 가 없다는 이유로 통째로 버려져, Properties 에는 보이는 disabled 가
   * 생성 코드에는 빠져 있었다.
   */
  globalStates: Record<string, SpecEntry>;
}

/** `button-primary48` → {variant:'primary', size:'48'} / `button-primary-hover` → state */
/**
 * 스펙 엔트리를 변형·크기·상태 축으로 가른다.
 * `prefix` 는 변형 키에서 떼어낼 앞부분 — 아키타입 이름(button) 또는 base 이름(icon-button).
 * 가이드 견본은 아키타입을, 생성기는 base 를 넘긴다.
 */
export function groupEntries(prefix: Archetype | string, list: SpecEntry[]): ArchGroup {
  const arch = prefix as Archetype;
  const variants = new Map<string, VariantGroup>();
  const sizes = new Map<string, SpecEntry>();
  for (const e of list) {
    const state = e.name.match(SPEC_STATE_SUFFIX_RE)?.[1];
    const stripped = e.name.replace(SPEC_STATE_SUFFIX_RE, '');
    const sizeM = stripped.match(/^(.*?)(\d{2,3})$/);
    const rawKey = (sizeM ? sizeM[1] : stripped).replace(new RegExp(`^${arch}-?`), '') || 'default';
    const key = rawKey.replace(/-+$/, '') || 'default';
    if (sizeM && !state && !sizes.has(sizeM[2])) sizes.set(sizeM[2], e);
    const v = variants.get(key) ?? { key, states: {} };
    if (state) v.states[state] = e;
    else if (!v.base) v.base = e;
    variants.set(key, v);
  }
  const globalStates: Record<string, SpecEntry> = {};
  for (const v of variants.values()) {
    if (v.base) continue;
    for (const [st, e] of Object.entries(v.states)) if (!globalStates[st]) globalStates[st] = e;
  }
  return {
    arch,
    variants: [...variants.values()].filter((v) => v.base),
    sizes: [...sizes.entries()].sort((a, b) => Number(b[0]) - Number(a[0])),
    entries: list,
    globalStates,
  };
}

/* ── 코드 조립 ── */

const ARCH_META: Record<Exclude<Archetype, 'other'>, { comp: string; title: string; desc: string }> = {
  button: { comp: 'Button', title: 'Button', desc: '버튼' },
  input: { comp: 'Input', title: 'Input', desc: '입력 필드' },
  badge: { comp: 'Badge', title: 'Badge', desc: '배지·태그' },
  nav: { comp: 'Nav', title: 'Navigation', desc: '내비게이션 바' },
  card: { comp: 'Card', title: 'Card', desc: '카드 컨테이너' },
  band: { comp: 'Band', title: 'Band', desc: '섹션 밴드' },
  toggle: { comp: 'Toggle', title: 'Toggle', desc: '토글 스위치' },
  checkbox: { comp: 'Checkbox', title: 'Checkbox', desc: '체크박스' },
  radio: { comp: 'Radio', title: 'Radio', desc: '라디오 버튼' },
  tab: { comp: 'Tab', title: 'Tab', desc: '탭' },
  segment: { comp: 'Segment', title: 'Segment', desc: '세그먼트 컨트롤' },
  cell: { comp: 'Cell', title: 'Cell', desc: '정사각·원형 셀' },
};

const q = (s: string) => `'${s.replace(/'/g, "\\'")}'`;

/** 스타일 쌍 목록 → `key: 'value',` 줄 (지정 들여쓰기) */
const styleLines = (pairs: Array<[string, string]>, indent: string): string =>
  pairs.map(([k, v]) => `${indent}${k}: ${q(v)},`).join('\n');

const parsePx = (v: string | undefined): number | null => {
  const m = v?.trim().match(/^(-?[\d.]+)px$/);
  return m ? Number(m[1]) : null;
};

interface BuildCtx {
  group: ArchGroup;
  tokens: DesignTokenMap;
  v2v: Map<string, string>;
  systemName: string;
}

function headerComment(ctx: BuildCtx, meta: { title: string }): string {
  const names = ctx.group.entries.map((e) => e.name);
  const shown = names.slice(0, 8).join(', ') + (names.length > 8 ? ` 외 ${names.length - 8}개` : '');
  return [
    '/**',
    ` * ${meta.title} — ${ctx.systemName} 디자인 시스템 스펙에서 ${GENERATED_CODE_MARK}.`,
    ` * 원본 스펙: ${shown}`,
    ' * 값은 토큰 변수(var(--…))로 연결돼 있어 토큰이 바뀌면 함께 반영됩니다.',
    ' * 이 파일을 직접 고치면 DESIGN.md 재업로드 시 갱신분에 덮여 유실될 수 있습니다.',
    ' */',
  ].join('\n');
}

/**
 * 두 축 분리 — SIZES 는 치수만, VARIANTS 는 색만.
 * 스펙 엔트리 하나(button-primary48)가 치수·색을 다 갖고 있어 그대로 두면 size 를 바꿀 때
 * 색까지 따라 바뀌어 variant 와 충돌한다.
 */
/** skip 집합 합성 (호출부 skip + 축 분리 skip) */
const union = (a: Set<string> | undefined, b: Set<string>): Set<string> => new Set([...(a ?? []), ...b]);

const SIZE_SKIP = new Set(['backgroundColor', 'color', 'borderColor', 'borderStyle']);
const VARIANT_SKIP = new Set(['borderRadius', 'padding', 'height', 'width', 'font']);

/** variant/size 상수 테이블 + 타입 선언 */
function tables(ctx: BuildCtx, comp: string, skip?: Set<string>): { types: string; consts: string; hasVariant: boolean; hasSize: boolean } {
  const { group, tokens, v2v } = ctx;
  const hasSize = group.sizes.length > 1;
  const hasVariant = group.variants.length > 1;
  const parts: string[] = [];
  const types: string[] = [];

  if (hasSize) {
    types.push(`type ${comp}Size = ${group.sizes.map(([s]) => q(s)).join(' | ')};`);
    parts.push(
      `const SIZES: Record<${comp}Size, React.CSSProperties> = {\n` +
        group.sizes
          .map(([s, e]) => `  ${q(s)}: {\n${styleLines(specToStyle(e, tokens, v2v, union(skip, SIZE_SKIP)), '    ')}\n  },`)
          .join('\n') +
        '\n};',
    );
  }
  if (hasVariant) {
    types.push(`type ${comp}Variant = ${group.variants.map((v) => q(v.key)).join(' | ')};`);
    const rows = group.variants.map((v) => {
      const seg: string[] = [`  ${q(v.key)}: {`];
      seg.push(`    base: {\n${styleLines(specToStyle(v.base, tokens, v2v, union(skip, VARIANT_SKIP)), '      ')}\n    },`);
      for (const st of ['hover', 'disabled'] as const) {
        if (v.states[st]) {
          seg.push(`    ${st}: {\n${styleLines(specToStyle(v.states[st], tokens, v2v, union(skip, VARIANT_SKIP)), '      ')}\n    },`);
        }
      }
      seg.push('  },');
      return seg.join('\n');
    });
    parts.push(
      `const VARIANTS: Record<${comp}Variant, { base: React.CSSProperties; hover?: React.CSSProperties; disabled?: React.CSSProperties }> = {\n` +
        rows.join('\n') +
        '\n};',
    );
  }
  if (!hasVariant && !hasSize) {
    // 단일 엔트리 — 상수 하나로
    parts.push(`const BASE: React.CSSProperties = {\n${styleLines(specToStyle(group.variants[0]?.base, tokens, v2v, skip), '  ')}\n};`);
  }
  return { types: types.join('\n'), consts: parts.join('\n\n'), hasVariant, hasSize };
}

/** 스타일 합성 식 — 템플릿 공통 */
function styleExpr(hasVariant: boolean, hasSize: boolean, extra: string[] = [], interactive = true, hasGlobalDisabled = false): string {
  const parts = [...extra];
  if (hasSize) parts.push('...SIZES[size]');
  if (hasVariant) parts.push('...v.base');
  if (!hasVariant && !hasSize) parts.push('...BASE');
  if (hasVariant && interactive) {
    parts.push("...(hovered && !disabled ? v.hover : null)", '...(disabled ? v.disabled : null)');
  }
  if (hasGlobalDisabled) {
    parts.push('...(disabled ? DISABLED : null)');
  }
  parts.push('...style');
  return parts.join(',\n        ');
}

function buildInteractive(ctx: BuildCtx, meta: { comp: string; title: string }): string {
  const { comp } = meta;
  const { types, consts, hasVariant, hasSize } = tables(ctx, comp);
  // 변형과 무관한 전역 disabled 스펙(`button-disabled`) — 있으면 모든 변형에 공통 적용
  const gDisabled = specToStyle(ctx.group.globalStates?.disabled, ctx.tokens, ctx.v2v);
  const disabledConst = gDisabled.length > 0
    ? `const DISABLED: React.CSSProperties = {\n${styleLines(gDisabled, '  ')}\n};`
    : '';
  const propLines = [
    hasVariant ? `  variant?: ${comp}Variant;` : null,
    hasSize ? `  size?: ${comp}Size;` : null,
  ].filter(Boolean);
  const defaults = [
    hasVariant ? `variant = ${q(ctx.group.variants[0].key)}` : null,
    hasSize ? `size = ${q(ctx.group.sizes[0][0])}` : null,
    'disabled',
    'style',
    'children',
    '...rest',
  ].filter(Boolean);
  return [
    headerComment(ctx, meta),
    "import React, { useState } from 'react';",
    '',
    types,
    '',
    `interface ${comp}Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {`,
    ...propLines,
    '}',
    '',
    consts,
    disabledConst ? '\n' + disabledConst : '',
    '',
    `export default function ${comp}({ ${defaults.join(', ')} }: ${comp}Props) {`,
    '  const [hovered, setHovered] = useState(false);',
    hasVariant ? '  const v = VARIANTS[variant];' : '',
    '  return (',
    '    <button',
    '      type="button"',
    '      disabled={disabled}',
    '      onMouseEnter={() => setHovered(true)}',
    '      onMouseLeave={() => setHovered(false)}',
    '      style={{',
    "        display: 'inline-flex',",
    "        alignItems: 'center',",
    "        justifyContent: 'center',",
    "        boxSizing: 'border-box',",
    "        border: 'none',",
    "        cursor: disabled ? 'not-allowed' : 'pointer',",
    `        ${styleExpr(hasVariant, hasSize, [], true, disabledConst !== '')},`,
    '      }}',
    '      {...rest}',
    '    >',
    '      {children}',
    '    </button>',
    '  );',
    '}',
    '',
  ]
    .filter((l) => l !== '')
    .join('\n')
    .replace(/\n{3,}/g, '\n\n');
}

function buildInput(ctx: BuildCtx, meta: { comp: string; title: string }): string {
  const { comp } = meta;
  const { types, consts, hasVariant, hasSize } = tables(ctx, comp);
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    types,
    '',
    // 네이티브 size 는 number(글자 수)라 우리 사이즈 축(문자열)과 타입이 충돌한다 — 있을 때만 걷어낸다
    hasSize
      ? `interface ${comp}Props extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {`
      : `interface ${comp}Props extends React.InputHTMLAttributes<HTMLInputElement> {`,
    hasVariant ? `  variant?: ${comp}Variant;` : '',
    hasSize ? `  size?: ${comp}Size;` : '',
    '}',
    '',
    consts,
    '',
    `export default function ${comp}({ ${[
      hasVariant ? `variant = ${q(ctx.group.variants[0].key)}` : null,
      hasSize ? `size = ${q(ctx.group.sizes[0][0])}` : null,
      'style',
      '...rest',
    ]
      .filter(Boolean)
      .join(', ')} }: ${comp}Props) {`,
    hasVariant ? '  const v = VARIANTS[variant];' : '',
    '  return (',
    '    <input',
    '      style={{',
    "        boxSizing: 'border-box',",
    "        width: '100%',",
    "        outline: 'none',",
    `        ${styleExpr(hasVariant, hasSize, [], false)},`,
    '      }}',
    '      {...rest}',
    '    />',
    '  );',
    '}',
    '',
  ]
    .filter((l) => l !== '')
    .join('\n')
    .replace(/\n{3,}/g, '\n\n');
}

/** 정적 컨테이너 (badge/card/nav/band/segment) */
function buildContainer(
  ctx: BuildCtx,
  meta: { comp: string; title: string },
  el: string,
  extraStyle: Array<[string, string]>,
  opts?: {
    /** 한 변이 같은 셀 — 스펙이 height 만 주는 관례라 width 를 같이 묶어 정사각을 보장한다 */
    squareFromHeight?: boolean;
  },
): string {
  const { comp } = meta;
  const { types, consts, hasVariant, hasSize } = tables(ctx, comp);
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    types,
    '',
    `interface ${comp}Props extends React.HTMLAttributes<HTMLDivElement> {`,
    hasVariant ? `  variant?: ${comp}Variant;` : '',
    hasSize ? `  size?: ${comp}Size;` : '',
    '}',
    '',
    consts,
    '',
    `export default function ${comp}({ ${[
      hasVariant ? `variant = ${q(ctx.group.variants[0].key)}` : null,
      hasSize ? `size = ${q(ctx.group.sizes[0][0])}` : null,
      'style',
      'children',
      '...rest',
    ]
      .filter(Boolean)
      .join(', ')} }: ${comp}Props) {`,
    hasVariant ? '  const v = VARIANTS[variant];' : '',
    '  return (',
    `    <${el}`,
    '      style={{',
    "        boxSizing: 'border-box',",
    // 스펙이 height 만 주는 관례라, 정사각 셀은 비율로 한 변을 묶는다
    ...(opts?.squareFromHeight ? ["        aspectRatio: '1 / 1',"] : []),
    ...extraStyle.map(([k, v]) => `        ${k}: ${q(v)},`),
    `        ${styleExpr(hasVariant, hasSize, [], false)},`,
    '      }}',
    '      {...rest}',
    '    >',
    '      {children}',
    `    </${el}>`,
    '  );',
    '}',
    '',
  ]
    .filter((l) => l !== '')
    .join('\n')
    .replace(/\n{3,}/g, '\n\n');
}

/** 토글 — 트랙 + 썸 (controlled) */
function buildToggle(ctx: BuildCtx, meta: { comp: string; title: string }): string {
  const { comp } = meta;
  const base = ctx.group.variants[0]?.base;
  const onState = ctx.group.variants[0]?.states.selected ?? ctx.group.variants[0]?.states.active;
  const h = parsePx(base?.props.height) ?? 30;
  const w = parsePx(base?.props.width) ?? Math.round(h * 1.75);
  const thumb = Math.max(10, h - 6);
  const onStyle = specToStyle(onState ?? base, ctx.tokens, ctx.v2v, new Set(['height', 'width', 'padding']));
  const offBg = toCssValue(base?.props.offBackgroundColor, ctx.tokens, ctx.v2v);
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    `interface ${comp}Props {`,
    '  checked?: boolean;',
    '  onChange?: (next: boolean) => void;',
    '  disabled?: boolean;',
    '  style?: React.CSSProperties;',
    '}',
    '',
    `const ON: React.CSSProperties = {\n${styleLines(onStyle, '  ')}\n};`,
    '',
    `export default function ${comp}({ checked = false, onChange, disabled, style }: ${comp}Props) {`,
    '  return (',
    '    <button',
    '      type="button"',
    '      role="switch"',
    '      aria-checked={checked}',
    '      disabled={disabled}',
    '      onClick={() => onChange?.(!checked)}',
    '      style={{',
    "        display: 'inline-flex',",
    "        alignItems: 'center',",
    `        justifyContent: checked ? 'flex-end' : 'flex-start',`,
    `        width: ${w},`,
    `        height: ${h},`,
    '        padding: 3,',
    "        boxSizing: 'border-box',",
    `        borderRadius: ${q(toCssValue(base?.props.rounded ?? base?.props.radius, ctx.tokens, ctx.v2v) ?? '999px')},`,
    "        border: 'none',",
    `        cursor: disabled ? 'not-allowed' : 'pointer',`,
    '        opacity: disabled ? 0.5 : 1,',
    `        background: checked ? (ON.backgroundColor as string) : ${q(offBg ?? '#CBD5E1')},`,
    '        ...style,',
    '      }}',
    '    >',
    '      <span',
    '        style={{',
    `          width: ${thumb},`,
    `          height: ${thumb},`,
    "          borderRadius: '50%',",
    "          background: '#FFFFFF',",
    "          boxShadow: '0 1px 2px rgba(0,0,0,0.25)',",
    '        }}',
    '      />',
    '    </button>',
    '  );',
    '}',
    '',
  ].join('\n');
}

/** 체크박스·라디오 — 박스/원 + 마크 (controlled) */
function buildCheck(ctx: BuildCtx, meta: { comp: string; title: string }, kind: 'checkbox' | 'radio'): string {
  const { comp } = meta;
  const base = ctx.group.variants[0]?.base;
  const size = parsePx(base?.props.height) ?? parsePx(base?.props.width) ?? 20;
  const fill = toCssValue(base?.props.backgroundColor, ctx.tokens, ctx.v2v) ?? 'currentColor';
  const border = toCssValue(base?.props.borderColor, ctx.tokens, ctx.v2v) ?? fill;
  const radius = kind === 'radio' ? "'50%'" : q(toCssValue(base?.props.rounded ?? base?.props.radius, ctx.tokens, ctx.v2v) ?? '4px');
  const mark =
    kind === 'checkbox'
      ? [
          '      {checked && (',
          '        <svg viewBox="0 0 16 16" width={Math.round(SIZE * 0.7)} height={Math.round(SIZE * 0.7)} aria-hidden>',
          '          <path d="M3.5 8.5l3 3 6-6.5" fill="none" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />',
          '        </svg>',
          '      )}',
        ]
      : [
          '      {checked && (',
          '        <span',
          '          style={{',
          '            width: Math.max(6, SIZE - 10),',
          '            height: Math.max(6, SIZE - 10),',
          "            borderRadius: '50%',",
          '            background: FILL,',
          '          }}',
          '        />',
          '      )}',
        ];
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    `interface ${comp}Props {`,
    '  checked?: boolean;',
    '  onChange?: (next: boolean) => void;',
    '  disabled?: boolean;',
    '  style?: React.CSSProperties;',
    '}',
    '',
    `const SIZE = ${size};`,
    `const FILL = ${q(fill)};`,
    `const BORDER = ${q(border)};`,
    '',
    `export default function ${comp}({ checked = false, onChange, disabled, style }: ${comp}Props) {`,
    '  return (',
    '    <button',
    '      type="button"',
    `      role="${kind}"`,
    '      aria-checked={checked}',
    '      disabled={disabled}',
    '      onClick={() => onChange?.(!checked)}',
    '      style={{',
    "        display: 'inline-flex',",
    "        alignItems: 'center',",
    "        justifyContent: 'center',",
    '        width: SIZE,',
    '        height: SIZE,',
    "        boxSizing: 'border-box',",
    `        borderRadius: ${radius},`,
    kind === 'checkbox'
      ? "        background: checked ? FILL : 'transparent',"
      : "        background: 'transparent',",
    '        border: `${checked ? 2 : 1.5}px solid ${checked ? BORDER : \'#CBD5E1\'}`,',
    '        padding: 0,',
    `        cursor: disabled ? 'not-allowed' : 'pointer',`,
    '        opacity: disabled ? 0.5 : 1,',
    '        ...style,',
    '      }}',
    '    >',
    ...mark,
    '    </button>',
    '  );',
    '}',
    '',
  ].join('\n');
}

/** 탭 — 선택 상태 + 하단 인디케이터 */
/**
 * 선택 표시에 쓸 강조색 — 스펙이 선택 상태를 안 적어둔 시스템(트랙만 기술)에서 폴백으로 쓴다.
 * 토큰에 **실존하는 값**만 반환한다(toCssValue 가 var 로 역매핑하므로 미정의 변수가 생기지 않는다).
 */
function pickAccentValue(tokens: DesignTokenMap): string | undefined {
  const color = tokens.color ?? tokens.colors ?? {};
  const rank = (k: string): number =>
    (/^(accent|primary|brand)(-|$)/.test(k) ? 0 : /(accent|primary|brand)/.test(k) ? 1 : 9)
    + (/(normal|base|default|main)(-|$)/.test(k) ? 0 : 0.5)
    + (/(hover|pressed|active|disabled|weak|light|neutral)/.test(k) ? 3 : 0);
  const best = Object.keys(color)
    .filter((k) => rank(k) < 9 && /^#|^rgb/.test(color[k]?.trim() ?? ''))
    .sort((a, b) => rank(a) - rank(b))[0];
  return best ? color[best] : undefined;
}

/**
 * 세그먼트 — 트랙 + 항목이 한 벌이라야 쓸 수 있다. 컨테이너만 만들면 개발자가
 * 항목·선택 표시를 직접 짜야 하고, 그 순간 디자인 시스템 밖으로 나간다.
 */
function buildSegment(ctx: BuildCtx, meta: { comp: string; title: string }): string {
  const { comp } = meta;
  const base = ctx.group.variants[0]?.base;
  const selected = ctx.group.variants[0]?.states.selected ?? ctx.group.variants[0]?.states.active;
  const trackStyle = specToStyle(base, ctx.tokens, ctx.v2v);
  const selStyle = specToStyle(selected, ctx.tokens, ctx.v2v, new Set(['height', 'padding']));
  // 선택 스펙이 없으면 강조 토큰으로 채운다 — 가이드 견본과 같은 폴백이라 화면과 코드가 어긋나지 않는다
  const accentRaw = selected ? undefined : pickAccentValue(ctx.tokens);
  const accent = accentRaw ? toCssValue(accentRaw, ctx.tokens, ctx.v2v) : null;
  const onAccentRaw = ctx.tokens.color?.['static-white'] ?? ctx.tokens.colors?.['static-white'];
  const onAccent = onAccentRaw ? toCssValue(onAccentRaw, ctx.tokens, ctx.v2v) : null;
  const fallbackSel = accent
    ? [`  background: ${q(accent)},`.replace(',', ','), `  color: ${q(onAccent ?? '#FFFFFF')},`]
    : ['  fontWeight: 700,'];
  const radiusRaw = trackStyle.find(([k]) => k === 'borderRadius')?.[1];
  const radius = radiusRaw ? q(String(radiusRaw)) : q('inherit');
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    `interface ${comp}Item {`,
    '  value: string;',
    '  label: React.ReactNode;',
    '  disabled?: boolean;',
    '}',
    '',
    `interface ${comp}Props extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {`,
    `  items: ${comp}Item[];`,
    '  value?: string;',
    '  onChange?: (next: string) => void;',
    '  /** 선택 항목 스타일 덮어쓰기 (브랜드 스펙에 선택 상태가 없을 때 조정용) */',
    '  selectedStyle?: React.CSSProperties;',
    '}',
    '',
    `const TRACK: React.CSSProperties = {\n${styleLines(trackStyle, '  ')}\n};`,
    '',
    selStyle.length > 0
      ? `const SELECTED: React.CSSProperties = {\n${styleLines(selStyle, '  ')}\n};`
      : `const SELECTED: React.CSSProperties = {\n${fallbackSel.join('\n')}\n};`,
    '',
    `export default function ${comp}({ items, value, onChange, selectedStyle, style, ...rest }: ${comp}Props) {`,
    '  const current = value ?? items[0]?.value;',
    '  return (',
    '    <div',
    '      role="group"',
    '      style={{',
    "        boxSizing: 'border-box',",
    "        display: 'inline-flex',",
    "        alignItems: 'stretch',",
    "        gap: '2px',",
    '        ...TRACK,',
    '        ...style,',
    '      }}',
    '      {...rest}',
    '    >',
    '      {items.map((item) => {',
    '        const on = item.value === current;',
    '        return (',
    '          <button',
    '            key={item.value}',
    '            type="button"',
    '            aria-pressed={on}',
    '            disabled={item.disabled}',
    '            onClick={() => onChange?.(item.value)}',
    '            style={{',
    "              flex: '1 1 auto',",
    "              display: 'inline-flex',",
    "              alignItems: 'center',",
    "              justifyContent: 'center',",
    "              padding: '0 14px',",
    "              border: 'none',",
    "              background: 'transparent',",
    "              color: 'inherit',",
    "              font: 'inherit',",
    `              borderRadius: ${radius},`,
    "              cursor: item.disabled ? 'not-allowed' : 'pointer',",
    '              opacity: item.disabled ? 0.5 : 1,',
    '              ...(on ? SELECTED : null),',
    '              ...(on ? selectedStyle : null),',
    '            }}',
    '          >',
    '            {item.label}',
    '          </button>',
    '        );',
    '      })}',
    '    </div>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function buildTab(ctx: BuildCtx, meta: { comp: string; title: string }): string {
  const { comp } = meta;
  const base = ctx.group.variants[0]?.base;
  const selected = ctx.group.variants[0]?.states.selected ?? ctx.group.variants[0]?.states.active;
  const baseStyle = specToStyle(base, ctx.tokens, ctx.v2v, new Set(['backgroundColor']));
  const selStyle = specToStyle(selected, ctx.tokens, ctx.v2v, new Set(['backgroundColor', 'height', 'padding']));
  const accent = toCssValue(selected?.props.textColor ?? base?.props.backgroundColor, ctx.tokens, ctx.v2v) ?? 'currentColor';
  return [
    headerComment(ctx, meta),
    "import React from 'react';",
    '',
    `interface ${comp}Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {`,
    '  selected?: boolean;',
    '}',
    '',
    `const BASE: React.CSSProperties = {\n${styleLines(baseStyle, '  ')}\n};`,
    selStyle.length > 0 ? `\nconst SELECTED: React.CSSProperties = {\n${styleLines(selStyle, '  ')}\n};` : '\nconst SELECTED: React.CSSProperties = {};',
    '',
    `export default function ${comp}({ selected = false, style, children, ...rest }: ${comp}Props) {`,
    '  return (',
    '    <button',
    '      type="button"',
    '      role="tab"',
    '      aria-selected={selected}',
    '      style={{',
    "        display: 'inline-flex',",
    "        alignItems: 'center',",
    "        background: 'transparent',",
    "        border: 'none',",
    "        cursor: 'pointer',",
    "        boxSizing: 'border-box',",
    `        borderBottom: selected ? '2px solid ${accent}' : '2px solid transparent',`,
    '        ...BASE,',
    '        ...(selected ? SELECTED : null),',
    '        ...style,',
    '      }}',
    '      {...rest}',
    '    >',
    '      {children}',
    '    </button>',
    '  );',
    '}',
    '',
  ].join('\n');
}

/* ── 진입점 ── */

const SPEC_RESOURCE_NAME = 'spec-components';

/**
 * 파싱 결과 → 스펙 기반 생성 컴포넌트 목록.
 * `existingNames` 는 이미 완성 코드가 있는 컴포넌트 이름 — 관리자 코드가 항상 이긴다.
 */
export function buildSpecComponents(parsed: ParsedDesignSystem, existingNames: Set<string>): GeneratedComponent[] {
  const specRes = parsed.resources.find((r) => r.name === SPEC_RESOURCE_NAME);
  if (!specRes?.bodyMd) return [];
  const specs = parseComponentSpecs(specRes.bodyMd);
  if (specs.length === 0) return [];

  const v2v = buildValueToVar(parsed.tokens);

  /*
   * base 이름 단위로 묶는다. 아키타입 하나당 컴포넌트 하나로 묶으면 icon-button 이 Button 에,
   * avatar 와 status-dot 이 하나의 Cell 로 합쳐져 서로 다른 컴포넌트가 변형으로 뭉갠다.
   * 다만 엔트리가 하나뿐인 base(property-card 등)까지 쪼개면 목록이 파편화되므로,
   * 그런 것은 아키타입 대표 그룹으로 되돌려 흡수한다.
   */
  const byBase = new Map<string, { arch: Archetype; entries: SpecEntry[] }>();
  for (const sp of specs) {
    const arch = specArchetype(sp.name);
    if (arch === 'other') continue; // 마크업 골격을 추측할 수 없는 이름 — 스펙 문서로만 남김
    const base = specBaseName(sp.name);
    const slot = byBase.get(base) ?? { arch, entries: [] };
    slot.entries.push(sp);
    byBase.set(base, slot);
  }

  /*
   * 홑 엔트리 base 는 같은 아키타입의 가장 큰 base 로 흡수한다 (property-card 하나 때문에
   * 목록이 쪼개지는 것 방지). 흡수 대상이 자기 자신뿐이면 그대로 둔다.
   */
  const biggestOfArch = new Map<Archetype, string>();
  for (const [base, g] of byBase) {
    const cur = biggestOfArch.get(g.arch);
    if (!cur || (byBase.get(cur)?.entries.length ?? 0) < g.entries.length) biggestOfArch.set(g.arch, base);
  }
  for (const [base, g] of [...byBase]) {
    const big = biggestOfArch.get(g.arch);
    if (g.entries.length > 1 || !big || big === base) continue;
    byBase.get(big)!.entries.push(...g.entries);
    byBase.delete(base);
  }

  /** 아키타입별 base 개수 — 하나뿐이면 아키타입 이름을 쓴다(기존 이름 보존) */
  const baseCountOfArch = new Map<Archetype, number>();
  for (const [, g] of byBase) baseCountOfArch.set(g.arch, (baseCountOfArch.get(g.arch) ?? 0) + 1);

  const out: GeneratedComponent[] = [];
  // 아키타입 순서 고정 (결정성) — 같은 아키타입 안에서는 base 이름 사전순
  const ORDER: Archetype[] = ['button', 'input', 'badge', 'toggle', 'checkbox', 'radio', 'tab', 'segment', 'cell', 'card', 'nav', 'band'];
  const groups = [...byBase.entries()]
    .filter(([, g]) => ORDER.includes(g.arch))
    .sort(([ba, ga], [bb, gb]) =>
      ORDER.indexOf(ga.arch) - ORDER.indexOf(gb.arch) || ba.localeCompare(bb, 'en-US'));

  for (const [base, g] of groups) {
    const arch = g.arch;
    const list = g.entries;
    const archMeta = ARCH_META[arch as Exclude<Archetype, 'other'>];
    /*
     * 그 아키타입에 base 가 하나뿐이면 아키타입 이름을 쓴다 — text-input 하나뿐인 시스템에서
     * 컴포넌트 이름이 'input' 으로 유지돼야 이미 발행된 시스템의 조회가 깨지지 않는다.
     * 둘 이상이면 각자 base 이름을 써야 구분된다 (button ↔ icon-button, avatar ↔ status-dot).
     */
    const sole = (baseCountOfArch.get(arch) ?? 0) <= 1;
    const compName = sole ? arch : base;
    const meta = sole
      ? archMeta
      : { comp: toPascalName(base), title: toTitleName(base), desc: archMeta.desc };
    if (existingNames.has(compName)) continue;
    const group = groupEntries(base, list);
    if (group.variants.length === 0) continue;
    const ctx: BuildCtx = { group, tokens: parsed.tokens, v2v, systemName: parsed.name };

    let code: string;
    switch (arch) {
      case 'button':
        code = buildInteractive(ctx, meta);
        break;
      case 'input':
        code = buildInput(ctx, meta);
        break;
      case 'toggle':
        code = buildToggle(ctx, meta);
        break;
      case 'checkbox':
      case 'radio':
        code = buildCheck(ctx, meta, arch);
        break;
      case 'tab':
        code = buildTab(ctx, meta);
        break;
      case 'badge':
        code = buildContainer(ctx, meta, 'span', [['display', 'inline-flex'], ['alignItems', 'center']]);
        break;
      case 'cell':
        // 한 변이 같은 셀 — width 를 height 와 묶어 정사각을 보장한다(스펙이 height 만 주는 관례)
        code = buildContainer(ctx, meta, 'span', [
          ['display', 'inline-flex'], ['alignItems', 'center'], ['justifyContent', 'center'], ['flex', 'none'],
        ], { squareFromHeight: true });
        break;
      case 'segment':
        code = buildSegment(ctx, meta);
        break;
      case 'nav':
        code = buildContainer(ctx, meta, 'nav', [['display', 'flex'], ['alignItems', 'center'], ['gap', '16px']]);
        break;
      case 'card':
      case 'band':
        code = buildContainer(ctx, meta, arch === 'card' ? 'div' : 'section', []);
        break;
      default:
        continue;
    }

    const usage: string[] = [
      `${meta.title} 은 브랜드 컴포넌트 스펙 ${group.entries.length}개에서 ${GENERATED_MARK}`,
      '',
      `- 원본 스펙: ${group.entries.map((e) => `\`${e.name}\``).join(', ')}`,
    ];
    if (group.variants.length > 1) usage.push(`- variant: ${group.variants.map((v) => `\`${v.key}\``).join(', ')}`);
    if (group.sizes.length > 1) usage.push(`- size: ${group.sizes.map(([s]) => `\`${s}\``).join(', ')}`);
    usage.push(
      '- 스타일 값은 토큰 변수(var(--…))로 연결 — 토큰이 바뀌면 함께 반영됩니다.',
      '- 마크업 골격은 표준 템플릿입니다. 스펙에 없는 구조(아이콘 슬롯·레이아웃)는 사용처에서 children 으로 채우세요.',
    );

    out.push({
      name: compName,
      title: meta.title,
      description: `${meta.desc} — 브랜드 스펙 자동 생성 (${group.entries.length}개 엔트리)`,
      code: code.trimEnd() + '\n',
      usageMd: usage.join('\n'),
      sourceEntries: group.entries.map((e) => e.name),
    });
  }
  return out;
}
