// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designConstants.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 디자인 시스템 캡·형식 — 서버 검증(designValidation.ts)과 클라 프리검증의 단일 소스.
 * Node 의존(path/Buffer) 없음 → 클라이언트 번들에 안전하게 포함 가능.
 *
 * ⚠️ *_MAX_BYTES 값은 supabase/migrations/000_baseline.sql §3.5~3.6(design_systems /
 * design_system_items)의 DB CHECK 와 반드시 동일 유지. 값을 바꾸려면 후속 마이그레이션이 필요하다.
 * (구 011_design_systems.sql 은 2026-08-26 baseline 통합으로 흡수됨)
 */

/** DESIGN.md 원문 최대 바이트 — design_systems.raw_content CHECK(524288) 와 쌍 */
export const DESIGN_RAW_MAX_BYTES = 512 * 1024; // 512KB

/** 컴포넌트 코드 1건 최대 바이트 — design_system_items.code CHECK(65536) 와 쌍 */
export const DESIGN_CODE_MAX_BYTES = 64 * 1024; // 64KB

/** Usage/Variants 서브섹션 각각 최대 바이트 — usage_md/variants_md CHECK(16384) 와 쌍 */
export const DESIGN_USAGE_MAX_BYTES = 16 * 1024; // 16KB

/** 리소스(참조 문서) 본문 최대 바이트 — body_md CHECK(102400) 와 쌍 (스킬 본문 캡과 동일) */
export const DESIGN_RESOURCE_MAX_BYTES = 102400; // 100KB

/** overview 산문 최대 바이트 — overview_md CHECK(102400) 와 쌍 */
export const DESIGN_OVERVIEW_MAX_BYTES = 102400; // 100KB

/** tokens/themes JSONB 직렬화 각각 최대 바이트 — CHECK(131072) 와 쌍 */
export const DESIGN_TOKENS_MAX_BYTES = 128 * 1024; // 128KB

/** 아이템(컴포넌트+리소스) 총 개수 상한 — 앱 레이어 전용(count 는 CHECK 불가) */
export const DESIGN_ITEMS_MAX = 200;
/** 컴포넌트 개수 상한 — 앱 레이어 전용 */
export const DESIGN_COMPONENTS_MAX = 100;
/** 테넌트당 디자인 시스템 개수 상한 — 앱 레이어 전용(POST 신규 생성 시 락 내부 count) */
export const DESIGN_SYSTEMS_PER_TENANT_MAX = 20;

/** 시스템·아이템 name 형식 — DB CHECK 정규식과 쌍 (스킬 name 규칙과 동일) */
export const DESIGN_NAME_RE = /^[a-z][a-z0-9-]*[a-z0-9]$/;
/** name 길이 (2~64) — DB CHECK 와 쌍 */
export const DESIGN_NAME_MIN = 2;
export const DESIGN_NAME_MAX = 64;

/** version 형식(semver) — DB CHECK 와 쌍 */
export const DESIGN_VERSION_RE = /^[0-9]+\.[0-9]+\.[0-9]+$/;

/** title 최대 길이 — DB CHECK(1~128) 와 쌍 */
export const DESIGN_TITLE_MAX = 128;
/** 시스템 description 최대 길이 — DB CHECK(1024) 와 쌍 */
export const DESIGN_DESCRIPTION_MAX = 1024;
/** 아이템 description 최대 길이 — DB CHECK(2048) 와 쌍 */
export const DESIGN_ITEM_DESCRIPTION_MAX = 2048;

/**
 * frontmatter 토큰 키 형식 — CSS 변수명(`--{category}-{key}`)으로 보간되므로 보수적.
 * 숫자 시작 허용(`2xl` 등 — CSS custom property 는 `--` 뒤 숫자 유효, 외부 생태계 관례).
 */
export const DESIGN_TOKEN_KEY_RE = /^[a-z0-9][a-z0-9-]*$/;
/** frontmatter 토큰 값 1건 최대 길이 */
export const DESIGN_TOKEN_VALUE_MAX = 256;
/**
 * frontmatter 토큰 값 화이트리스트 — CSS value 로 보간되므로 선택자 탈출 문자(`;{}`)와
 * 제어문자를 금지. 따옴표·쉼표·괄호는 폰트 스택(`'Pretendard', sans-serif`) 호환 위해 허용.
 */
export const DESIGN_TOKEN_VALUE_RE = /^[a-zA-Z0-9\s#%.,()'"\/_-]+$/;

/** 코드 언어 화이트리스트 — design_system_items.code_lang CHECK 와 쌍 */
export const DESIGN_CODE_LANGS = new Set(['tsx', 'jsx']);

/** AI 도구가 안내하는 저장 경로 규약 (스킬 본문·spec 문서와 단일 소스) */
export const DESIGN_TOKENS_CSS_PATH = 'styles/design-tokens.css';
export const DESIGN_COMPONENT_DIR = 'components/design';
/** 생성 앱의 브랜드 에셋(로고 SVG) 저장 디렉토리 — 도구 응답·프롬프트 규칙 단일 소스 */
export const DESIGN_BRAND_DIR = 'public/brand';
/** 도구 응답에 인라인하는 에셋(SVG 텍스트) 1건 상한 — 초과분은 목록 안내만 */
export const DESIGN_ASSET_INLINE_MAX_BYTES = 96 * 1024; // 96KB

/* ── 생성 스킬 번들 (zip: SKILL.md + references/ [+ assets/]) — buildSkillBundle ── */

/**
 * SKILL.md 본문에 인라인하는 토큰 CSS 상한 — 초과 시 `references/_tokens.md` 로 분리
 * (결정적 강등). `_` 접두는 아이템 슬러그 문자군([a-z0-9-]) 밖이라 참조 파일명과 충돌 불가.
 */
export const DESIGN_SKILL_TOKENS_INLINE_MAX_BYTES = 32 * 1024; // 32KB

/**
 * 번들 총량(SKILL.md + references 합) 상한 — 초과 시 컴포넌트 코드 파일을 제외한
 * '목록 모드'로 결정적 강등 (실패가 아님. 코드는 가이드 페이지에서 열람 가능).
 */
export const DESIGN_SKILL_BUNDLE_MAX_BYTES = 8 * 1024 * 1024; // 8MB

/* ── 브랜드 에셋 (로고 등 — 마이그 012 design_systems.assets JSONB 와 쌍) ── */

/** assets JSONB 직렬화 총량 — 012 CHECK(16384) 와 쌍, 동시 수정 필수 */
export const DESIGN_ASSETS_META_MAX_BYTES = 16384; // 16KB

/**
 * 에셋 종류 화이트리스트 — DB 는 enum 고정하지 않음(확장 개방), 여기가 게이트.
 * v1 UI 노출은 logo-full 만 (logo-mark·favicon 은 소비처 생기면 UI 슬롯 추가).
 */
export const DESIGN_ASSET_KINDS = new Set(['logo-full', 'logo-mark', 'favicon']);
export const DESIGN_ASSET_THEMES = new Set(['light', 'dark', 'any']);

/** 슬롯 수 상한(앱 레이어 — kind×theme 조합 수 기준) */
export const DESIGN_ASSET_SLOTS_MAX = 9;

/** 에셋 파일 1건 최대 바이트 (skills 버킷 1MB 선례) */
export const DESIGN_ASSET_FILE_MAX_BYTES = 1024 * 1024; // 1MB

/**
 * 허용 확장자 → MIME (ext 별 밸리데이터 레지스트리는 designAssetValidation.ts —
 * 여기 없는 확장자는 fail-closed reject. PNG 등 추가 = 이 맵 + 밸리데이터 1개 등록)
 */
export const DESIGN_ASSET_EXT_MIME: Record<string, string> = {
  svg: 'image/svg+xml',
};

/* ── AI 교정·조립 (designAiFix — 앱 레이어 캡, 클라 프리검증 공용) ── */

/** AI 입력 상한 — 단일 파일(repair)·다중 파일 합산(compose) 공통. 초과 시 미발동 */
export const DESIGN_FIX_INPUT_MAX_BYTES = 128 * 1024; // 128KB
/** compose 모드 자료 파일 수 상한 */
export const DESIGN_FIX_FILES_MAX = 10;

/**
 * AI 가 작성한 아이템 표시 (컴포넌트 코드·보강 문서) — usage_md 접두.
 * 재업로드 items 재구성에서 **보존 대상 판정 축**이라 designSystem/designComponentAi 양쪽이
 * 참조한다. 순환 import 를 피해 무의존 파일에 둔다.
 */
export const AI_AUTHORED_MARK = '<!-- design-md: ai-authored -->';

/** AI 문서 보강이 적용된 아이템 — 재실행 시 미보강분을 먼저 처리하기 위한 판정 축 */
export const AI_DOC_MARK = '<!-- design-md: ai-doc -->';

/**
 * 결정적 생성기가 만든 코드의 표식(코드 주석 안).
 * 재업로드 때 '이 코드는 다시 만들어도 되는가' 를 코드 자체로 판정하는 축 —
 * usage_md 마커는 문서 보강이 함께 건드리므로 코드 보존 판정에 쓸 수 없다.
 */
export const GENERATED_CODE_MARK = '자동 생성 (AI 미사용)';
