// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designLint.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * 디자인 품질 린트 — 자체 결정적 진단 (advisory 전용, 게이트 아님).
 *
 * 2026-07-29 결정: 공식 @google/design.md 린터 미도입 — 실측(프로브)상 우리 방언
 * (frontmatter `tokens:` 중첩)에서 토큰을 0개 인식해 파일별 변별력이 없고, 유용 룰
 * (missing-primary·대비 등)이 전부 미발화. 대신 우리 토큰 모델 기준으로 직접 구현 —
 * 100% 발화·의존 0·킷 COPIES 전파. AI 는 진단이 아니라 교정 단계(P4)에만 사용.
 *
 * 원칙:
 * - 결정적: 동일 파싱 결과 → 동일 진단 (룰 순서·경로 정렬 고정)
 * - advisory: 어떤 진단도 업로드/발행을 막지 않음 (거절은 designValidation 몫)
 * - 순수 코어: 상대 import 만 (킷 COPIES 대상 — 외부 의존 금지)
 */

import { type ParsedDesignSystem, type DesignTokenMap } from './designParser';

export interface DesignLintFinding {
  rule: string;
  severity: 'warning' | 'info';
  /** 대상 위치 (예: tokens.color, themes.dark.color, components.button) */
  path: string;
  message: string;
}

/* ── 유틸 ── */

/** 관례 카테고리 — 가이드 비주얼라이저 KNOWN·컴포넌트 var() 폴백과 맞물리는 이름들 */
const CONVENTION_CATEGORIES = ['color', 'typography', 'spacing', 'radius', 'shadow'];

function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i += 1) {
    const cur = [i];
    for (let j = 1; j <= n; j += 1) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = cur;
  }
  return prev[n];
}

/** #RGB/#RRGGBB/rgb()/rgba() → [r,g,b] 0~255. 그 외 형식은 null (진단 스킵) */
function parseColor(v: string): [number, number, number] | null {
  const s = v.trim();
  const hex3 = s.match(/^#([0-9a-fA-F]{3})$/);
  if (hex3) {
    const h = hex3[1];
    return [parseInt(h[0] + h[0], 16), parseInt(h[1] + h[1], 16), parseInt(h[2] + h[2], 16)];
  }
  const hex6 = s.match(/^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$/);
  if (hex6) {
    const h = hex6[1];
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
  }
  const rgb = s.match(/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})/);
  if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3])];
  return null;
}

/** WCAG 상대 휘도 (sRGB 선형화) */
function relativeLuminance([r, g, b]: [number, number, number]): number {
  const lin = (c: number) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/** WCAG 대비율 (1~21). 어느 한쪽이라도 파싱 불가면 null */
export function contrastRatio(a: string, b: string): number | null {
  const ca = parseColor(a);
  const cb = parseColor(b);
  if (!ca || !cb) return null;
  const la = relativeLuminance(ca);
  const lb = relativeLuminance(cb);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

const round1 = (n: number) => Math.round(n * 10) / 10;

/* ── 룰 ── */

/** ① 카테고리 오타/비관례 — 관례명과 거리 1~2 면 제안 (info) */
function ruleCategoryConvention(tokens: DesignTokenMap, out: DesignLintFinding[]) {
  for (const category of Object.keys(tokens).sort()) {
    if (CONVENTION_CATEGORIES.includes(category)) continue;
    let best: string | null = null;
    let bestDist = 3;
    for (const conv of CONVENTION_CATEGORIES) {
      const d = levenshtein(category, conv);
      if (d < bestDist) {
        bestDist = d;
        best = conv;
      }
    }
    if (best) {
      out.push({
        rule: 'category-convention',
        severity: 'info',
        path: `tokens.${category}`,
        message: `카테고리 "${category}" — 혹시 "${best}" 인가요? 관례 카테고리를 쓰면 가이드 페이지·컴포넌트 폴백(var(--${best}-…))과 맞물립니다.`,
      });
    }
  }
}

/**
 * ② 브랜드 색 부재 — 버튼·강조가 기본 파랑 폴백으로 렌더됨 (warning).
 * primary 정확 키만이 아니라 brand·accent 접두 계열도 인정 — 가이드 별칭 해석과 동기
 * (별칭이 잡아주는 이름에 경고하면 거짓 경고가 된다).
 */
function ruleMissingPrimary(tokens: DesignTokenMap, out: DesignLintFinding[]) {
  const color = tokens.color;
  if (!color || Object.keys(color).length === 0) return;
  if (!Object.keys(color).some((k) => /^(primary|brand|accent)/.test(k))) {
    out.push({
      rule: 'missing-primary',
      severity: 'warning',
      path: 'tokens.color',
      message: 'primary(또는 brand·accent 계열) 색 토큰이 없어요 — 버튼·강조·CTA 가 브랜드 색 대신 기본 파랑 폴백으로 렌더됩니다.',
    });
  }
}

/** ③ 다크 배경/글자 짝 깨짐 — 한쪽만 덮으면 다크에서 텍스트 실종 위험 (warning) */
function ruleDarkPairGap(themes: Record<string, DesignTokenMap>, out: DesignLintFinding[]) {
  const darkColor = themes.dark?.color;
  if (!darkColor) return;
  const hasSurface = 'surface' in darkColor;
  const hasText = 'text' in darkColor;
  if (hasSurface !== hasText) {
    const missing = hasSurface ? 'text' : 'surface';
    const present = hasSurface ? 'surface' : 'text';
    out.push({
      rule: 'dark-pair-gap',
      severity: 'warning',
      path: 'themes.dark.color',
      message: `다크 테마가 color.${present} 만 덮고 짝인 color.${missing} 는 라이트 값 그대로예요 — 다크 화면에서 글자·배경이 겹쳐 안 보일 수 있어요.`,
    });
  }
}

/** ④ 텍스트/배경 대비 미달 — WCAG AA 4.5:1 (warning). hex/rgb 만 판정, 그 외 형식 스킵 */
function ruleLowContrast(tokens: DesignTokenMap, themes: Record<string, DesignTokenMap>, out: DesignLintFinding[]) {
  const pairs: Array<[string, string | undefined, string | undefined]> = [
    ['tokens.color', tokens.color?.text, tokens.color?.surface],
    [
      'themes.dark.color',
      themes.dark?.color?.text ?? tokens.color?.text,
      themes.dark?.color?.surface ?? tokens.color?.surface,
    ],
  ];
  // 다크 테마 자체가 없으면 두 번째 쌍은 첫 쌍과 동일 — 중복 진단 방지
  const seen = new Set<string>();
  for (const [path, text, surface] of pairs) {
    if (!text || !surface) continue;
    const key = `${text}|${surface}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const ratio = contrastRatio(text, surface);
    if (ratio !== null && ratio < 4.5) {
      out.push({
        rule: 'low-contrast',
        severity: 'warning',
        path,
        message: `text(${text}) 와 surface(${surface}) 의 대비가 ${round1(ratio)}:1 이에요 — 본문 텍스트 권장(WCAG AA)은 4.5:1 이상입니다.`,
      });
    }
  }
}

/** ⑤ 컴포넌트 코드가 토큰 미사용 — hex 하드코딩만 있고 var(--) 참조 0회 (info) */
function ruleHardcodedColors(parsed: ParsedDesignSystem, out: DesignLintFinding[]) {
  for (const c of [...parsed.components].sort((a, b) => a.name.localeCompare(b.name, 'en-US'))) {
    const code = c.code ?? '';
    const hexCount = (code.match(/#[0-9a-fA-F]{3,8}\b/g) ?? []).length;
    const varCount = (code.match(/var\(\s*--/g) ?? []).length;
    if (hexCount >= 3 && varCount === 0) {
      out.push({
        rule: 'hardcoded-colors',
        severity: 'info',
        path: `components.${c.name}`,
        message: `"${c.title}" 코드가 색 ${hexCount}곳을 hex 로 하드코딩하고 토큰 변수(var(--…))를 쓰지 않아요 — 토큰 참조로 바꾸면 재발행만으로 리브랜딩됩니다.`,
      });
    }
  }
}

/**
 * 품질 진단 — 업로드 성공본에 대해 실행 (실패본은 designValidation issues[] 가 담당).
 * 반환 순서 고정: 룰 정의 순 → 경로 정렬 (결정성).
 */
export function lintDesignSystem(parsed: ParsedDesignSystem): DesignLintFinding[] {
  const out: DesignLintFinding[] = [];
  ruleCategoryConvention(parsed.tokens, out);
  ruleMissingPrimary(parsed.tokens, out);
  ruleDarkPairGap(parsed.themes, out);
  ruleLowContrast(parsed.tokens, parsed.themes, out);
  ruleHardcodedColors(parsed, out);
  return out;
}
