// AUTO-GENERATED by scripts/generate-design-kit.mjs — DO NOT EDIT.
// 원본(정본): src/lib/design/designParser.ts — 수정은 VibeAgent upstream 원본에서. 재생성: (VibeAgent repo 에서) node scripts/generate-design-kit.mjs (predev/prebuild 자동).

/**
 * DESIGN.md 프로토콜 v1 결정적 파서.
 *
 * 구조: YAML frontmatter(서브셋 — 맵·스칼라·중첩만) + 본문(`## Components` H3=컴포넌트,
 * `## Resources` H3=리소스, 규약 외 H2 는 overview 로 원문 보존).
 *
 * 결정성 원칙: 지원하지 않는 문법은 조용히 넘기지 않고 **파스 에러로 거절**한다
 * (YAML 시퀀스·앵커·블록 스칼라, 틸드·4+백틱·미종결 펜스, 컴포넌트 섹션 내 미지 헤딩).
 * 에러는 전부 수집 후 일괄 반환 — admin UI 가 한 번에 표시한다.
 *
 * 파싱은 업로드 시 1회. 소비(가이드 페이지·AI 도구)는 구조화 저장 데이터만 읽는다.
 */

import {
  DESIGN_NAME_RE,
  DESIGN_NAME_MIN,
  DESIGN_NAME_MAX,
  DESIGN_VERSION_RE,
  DESIGN_TITLE_MAX,
  DESIGN_CODE_LANGS,
} from './designConstants';

export interface ParseIssue {
  layer: 'structure' | 'prose' | 'code';
  path: string;
  message: string;
}

/** category → (flatten 된 key → 스칼라 값). 중첩 맵은 '-' 로 평탄화 (color.brand.primary → brand-primary) */
export type DesignTokenMap = Record<string, Record<string, string>>;

export interface ParsedComponent {
  name: string; // slug
  title: string;
  description: string;
  usageMd: string;
  variantsMd: string;
  code: string;
  codeLang: 'tsx' | 'jsx';
  position: number;
}

export interface ParsedResource {
  name: string; // slug
  title: string;
  bodyMd: string;
  position: number;
}

export interface ParsedDesignSystem {
  name: string;
  title: string;
  description: string;
  version: string;
  stack: string;
  tokens: DesignTokenMap;
  themes: Record<string, DesignTokenMap>; // v1: 'dark' 만 허용
  overviewMd: string;
  components: ParsedComponent[];
  resources: ParsedResource[];
}

export type ParseResult =
  | { ok: true; value: ParsedDesignSystem; issues: ParseIssue[] }
  | { ok: false; issues: ParseIssue[] };

/* ------------------------------------------------------------------ */
/* 펜스 문법 화이트리스트                                               */
/* ------------------------------------------------------------------ */

/** 인정 펜스 열기: 행두 0-indent 백틱 정확히 3개 + 단일 info 토큰 */
const FENCE_OPEN_RE = /^```([a-zA-Z0-9-]*)[ \t]*$/;
/** 닫기: 행두 ``` 단독 행 */
const FENCE_CLOSE_RE = /^```[ \t]*$/;
/** 거절 대상: 틸드 펜스 / 4+백틱 펜스 */
const TILDE_FENCE_RE = /^~~~/;
const LONG_FENCE_RE = /^````/;

const HEADING_RE = /^(#{1,6})\s+(.*)$/;

/** 서버가 서빙 시 선삽입하는 provenance 헤더 — 업로드 시 strip (fork round-trip 허용) */
const PROVENANCE_LINE_RE = /^\s*\/\/ @design-system /;

/** 제목 → slug (영문 kebab). 영숫자가 없으면 '' 반환 → 호출부에서 거절 */
export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
}

/* ------------------------------------------------------------------ */
/* YAML 서브셋 파서 (frontmatter 전용)                                  */
/* ------------------------------------------------------------------ */

type YamlNode = { [key: string]: string | YamlNode };

const YAML_KEY_RE = /^([A-Za-z0-9_-]+):(?:[ \t]+(.*))?$/;

function stripQuotes(v: string): string {
  const t = v.trim();
  if (t.length >= 2) {
    const first = t[0];
    const last = t[t.length - 1];
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return t.slice(1, -1);
    }
  }
  return t;
}

function parseYamlSubset(lines: string[], issues: ParseIssue[]): YamlNode {
  const root: YamlNode = {};
  const stack: Array<{ indent: number; node: YamlNode }> = [{ indent: -1, node: root }];

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    const path = `frontmatter:${i + 1}`;

    const leading = raw.match(/^[ \t]*/)?.[0] ?? '';
    if (leading.includes('\t')) {
      issues.push({ layer: 'structure', path, message: '들여쓰기에 탭을 쓸 수 없습니다(공백만 허용).' });
      continue;
    }
    const indent = leading.length;
    const body = raw.slice(indent);

    if (body.startsWith('- ') || body === '-') {
      issues.push({ layer: 'structure', path, message: 'YAML 시퀀스(-)는 지원하지 않습니다 — 맵/스칼라만 사용하세요.' });
      continue;
    }

    const m = body.match(YAML_KEY_RE);
    if (!m) {
      issues.push({ layer: 'structure', path, message: `해석할 수 없는 frontmatter 행입니다: "${body.slice(0, 40)}"` });
      continue;
    }
    const key = m[1];
    const rest = (m[2] ?? '').trim();

    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) stack.pop();
    const parent = stack[stack.length - 1].node;

    if (Object.prototype.hasOwnProperty.call(parent, key)) {
      issues.push({ layer: 'structure', path, message: `중복 키입니다: ${key}` });
      continue;
    }

    if (rest === '') {
      const child: YamlNode = {};
      parent[key] = child;
      stack.push({ indent, node: child });
      continue;
    }
    if (rest === '|' || rest === '>' || rest.startsWith('| ') || rest.startsWith('> ')) {
      issues.push({ layer: 'structure', path, message: `블록 스칼라(|,>)는 지원하지 않습니다: ${key}` });
      continue;
    }
    if (rest.startsWith('&') || rest.startsWith('*')) {
      issues.push({ layer: 'structure', path, message: `YAML 앵커/별칭(&,*)은 지원하지 않습니다: ${key}` });
      continue;
    }
    parent[key] = stripQuotes(rest);
  }
  return root;
}

/** 중첩 맵을 '-' 조인으로 평탄화 (스칼라만 leaf 허용) */
function flattenTokenCategory(
  node: YamlNode,
  categoryPath: string,
  issues: ParseIssue[],
): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (n: YamlNode, prefix: string) => {
    for (const [k, v] of Object.entries(n)) {
      const key = prefix ? `${prefix}-${k}` : k;
      if (typeof v === 'string') {
        out[key] = v;
      } else {
        walk(v, key);
      }
    }
  };
  walk(node, '');
  if (Object.keys(out).length === 0) {
    issues.push({ layer: 'structure', path: categoryPath, message: '빈 토큰 카테고리입니다.' });
  }
  return out;
}

function extractTokenMap(
  value: string | YamlNode | undefined,
  fieldPath: string,
  issues: ParseIssue[],
): DesignTokenMap {
  const map: DesignTokenMap = {};
  if (value === undefined) return map;
  if (typeof value === 'string') {
    issues.push({ layer: 'structure', path: fieldPath, message: '맵이어야 합니다(카테고리 → 키: 값).' });
    return map;
  }
  for (const [category, catNode] of Object.entries(value)) {
    if (typeof catNode === 'string') {
      issues.push({
        layer: 'structure',
        path: `${fieldPath}.${category}`,
        message: '카테고리는 맵이어야 합니다(예: color: { primary: "#..." }).',
      });
      continue;
    }
    map[category] = flattenTokenCategory(catNode, `${fieldPath}.${category}`, issues);
  }
  return map;
}

/* ------------------------------------------------------------------ */
/* 본문 파서 (줄 단위 상태기계)                                          */
/* ------------------------------------------------------------------ */

type Section = 'overview' | 'components' | 'resources';
type Subsection = 'description' | 'usage' | 'variants' | 'code';

export function parseDesignMd(raw: string): ParseResult {
  const issues: ParseIssue[] = [];
  const lines = raw.split(/\r\n|\r|\n/);

  // --- frontmatter 경계 ---
  if (lines[0]?.trim() !== '---') {
    return {
      ok: false,
      issues: [{ layer: 'structure', path: 'frontmatter', message: '파일이 `---` frontmatter 로 시작해야 합니다.' }],
    };
  }
  let fmEnd = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') {
      fmEnd = i;
      break;
    }
  }
  if (fmEnd === -1) {
    return {
      ok: false,
      issues: [{ layer: 'structure', path: 'frontmatter', message: 'frontmatter 닫는 `---` 가 없습니다.' }],
    };
  }

  const fm = parseYamlSubset(lines.slice(1, fmEnd), issues);

  // --- frontmatter 필드 ---
  const fmString = (key: string): string => {
    const v = fm[key];
    return typeof v === 'string' ? v : '';
  };
  const name = fmString('name');
  const version = fmString('version');
  const title = fmString('title') || name;
  const description = fmString('description');
  const stack = fmString('stack') || 'react-tailwind';

  if (!name) {
    issues.push({ layer: 'structure', path: 'frontmatter.name', message: 'name 은 필수입니다.' });
  } else if (name.length < DESIGN_NAME_MIN || name.length > DESIGN_NAME_MAX || !DESIGN_NAME_RE.test(name) || name.includes('--')) {
    issues.push({
      layer: 'structure',
      path: 'frontmatter.name',
      message: 'name 은 2~64자 소문자·숫자·하이픈(kebab-case)이어야 합니다.',
    });
  }
  if (!version) {
    issues.push({ layer: 'structure', path: 'frontmatter.version', message: 'version 은 필수입니다(예: 1.0.0).' });
  } else if (!DESIGN_VERSION_RE.test(version)) {
    issues.push({ layer: 'structure', path: 'frontmatter.version', message: 'version 은 semver(예: 1.0.0)여야 합니다.' });
  }
  if (title.length > DESIGN_TITLE_MAX) {
    issues.push({ layer: 'structure', path: 'frontmatter.title', message: `title 은 ${DESIGN_TITLE_MAX}자 이하여야 합니다.` });
  }
  if (stack !== 'react-tailwind') {
    issues.push({ layer: 'structure', path: 'frontmatter.stack', message: "v1 은 stack: react-tailwind 만 지원합니다." });
  }

  if (fm.tokens === undefined) {
    issues.push({ layer: 'structure', path: 'frontmatter.tokens', message: 'tokens 는 필수입니다.' });
  }
  const tokens = extractTokenMap(fm.tokens, 'frontmatter.tokens', issues);
  if (fm.tokens !== undefined && typeof fm.tokens !== 'string' && Object.keys(tokens).length === 0) {
    issues.push({ layer: 'structure', path: 'frontmatter.tokens', message: 'tokens 에 최소 1개 카테고리가 필요합니다.' });
  }

  const themes: Record<string, DesignTokenMap> = {};
  if (fm.themes !== undefined) {
    if (typeof fm.themes === 'string') {
      issues.push({ layer: 'structure', path: 'frontmatter.themes', message: 'themes 는 맵이어야 합니다.' });
    } else {
      for (const [themeName, themeNode] of Object.entries(fm.themes)) {
        if (themeName !== 'dark') {
          issues.push({
            layer: 'structure',
            path: `frontmatter.themes.${themeName}`,
            message: "v1 은 themes.dark 만 지원합니다.",
          });
          continue;
        }
        if (typeof themeNode === 'string') {
          issues.push({ layer: 'structure', path: 'frontmatter.themes.dark', message: 'themes.dark 는 맵이어야 합니다.' });
          continue;
        }
        themes[themeName] = extractTokenMap(themeNode, `frontmatter.themes.${themeName}`, issues);
      }
    }
  }

  // --- 본문 상태기계 ---
  const overviewLines: string[] = [];
  const components: ParsedComponent[] = [];
  const resources: ParsedResource[] = [];

  let section: Section = 'overview';
  let seenComponents = false;
  let seenResources = false;

  interface CompState {
    title: string;
    slug: string;
    descriptionLines: string[];
    usageLines: string[];
    variantsLines: string[];
    codeLines: string[];
    codeLang: 'tsx' | 'jsx' | null;
    codeFenceCount: number;
    sub: Subsection;
    seenSubs: Set<string>;
    headingLine: number;
  }
  interface ResState {
    title: string;
    slug: string;
    bodyLines: string[];
    headingLine: number;
  }
  // ⚠️ 상태 전이는 반드시 외부 루프에서 대입한다 (클로저 내 대입은 TS CFA 미추적 — never 내로잉)
  let curComponent: CompState | null = null;
  let curResource: ResState | null = null;

  let inFence = false;
  let fenceStartLine = 0;
  let fenceInfo = '';
  /** 펜스가 열린 위치의 수집 대상 (컴포넌트 코드 펜스는 codeLines 로) */
  let fenceSink: string[] | null = null;
  let fenceIsComponentCode = false;
  /** true 면 원문 보존 싱크(usage/variants/overview 등) — 닫는 ``` 라인도 보존 */
  let fencePreserveRaw = false;

  const usedSlugs = new Map<string, string>(); // slug(lower) → kind/title (중복 검사)

  const componentPath = () => `components/${curComponent?.slug ?? '?'}`;
  const resourcePath = () => `resources/${curResource?.slug ?? '?'}`;

  const flushComponent = (c: CompState | null): null => {
    if (!c) return null;
    if (c.codeLang === null || c.codeLines.length === 0) {
      issues.push({
        layer: 'structure',
        path: `components/${c.slug}`,
        message: '#### Code 에 ```tsx 또는 ```jsx 코드 블록이 필요합니다(필수 — AI 자동 생성은 후속 지원 예정).',
      });
      return null;
    }
    components.push({
      name: c.slug,
      title: c.title,
      description: c.descriptionLines.join('\n').trim(),
      usageMd: c.usageLines.join('\n').trim(),
      variantsMd: c.variantsLines.join('\n').trim(),
      code: c.codeLines.join('\n').replace(/\n+$/, '') + '\n',
      codeLang: c.codeLang,
      position: components.length,
    });
    return null;
  };

  const flushResource = (r: ResState | null): null => {
    if (!r) return null;
    const body = r.bodyLines.join('\n').trim();
    if (!body) {
      issues.push({ layer: 'structure', path: `resources/${r.slug}`, message: '리소스 본문이 비어 있습니다.' });
      return null;
    }
    resources.push({ name: r.slug, title: r.title, bodyMd: body + '\n', position: resources.length });
    return null;
  };

  const validateItemHeading = (kind: 'component' | 'resource', headingText: string): { t: string; slug: string } => {
    const t = headingText.trim();
    const slug = slugifyTitle(t);
    const path = `${kind}s/${slug || '?'}`;
    if (!t || t.length > DESIGN_TITLE_MAX) {
      issues.push({ layer: 'structure', path, message: `제목은 1~${DESIGN_TITLE_MAX}자여야 합니다.` });
    }
    if (!slug || slug.length < DESIGN_NAME_MIN || slug.length > DESIGN_NAME_MAX || !DESIGN_NAME_RE.test(slug)) {
      issues.push({
        layer: 'structure',
        path,
        message: `제목 "${t.slice(0, 40)}" 에서 유효한 영문 슬러그를 만들 수 없습니다 — 영문 이름을 사용하세요(예: Button).`,
      });
    }
    const dupKey = slug.toLowerCase();
    if (slug && usedSlugs.has(dupKey)) {
      issues.push({ layer: 'structure', path, message: `중복 이름입니다("${usedSlugs.get(dupKey)}" 와 충돌).` });
    } else if (slug) {
      usedSlugs.set(dupKey, t);
    }
    return { t, slug };
  };

  const openComponent = (headingText: string, lineNo: number): CompState => {
    const { t, slug } = validateItemHeading('component', headingText);
    return {
      title: t,
      slug,
      descriptionLines: [],
      usageLines: [],
      variantsLines: [],
      codeLines: [],
      codeLang: null,
      codeFenceCount: 0,
      sub: 'description',
      seenSubs: new Set(),
      headingLine: lineNo,
    };
  };

  const openResource = (headingText: string, lineNo: number): ResState => {
    const { t, slug } = validateItemHeading('resource', headingText);
    return { title: t, slug, bodyLines: [], headingLine: lineNo };
  };

  for (let i = fmEnd + 1; i < lines.length; i++) {
    const line = lines[i];
    const lineNo = i + 1;
    const path = () =>
      section === 'components' && curComponent
        ? componentPath()
        : section === 'resources' && curResource
          ? resourcePath()
          : `body:${lineNo}`;

    // --- 펜스 상태 ---
    if (inFence) {
      if (FENCE_CLOSE_RE.test(line)) {
        if (fencePreserveRaw) fenceSink?.push(line); // 원문 보존 싱크는 닫는 펜스도 유지
        inFence = false;
        fenceSink = null;
        fenceIsComponentCode = false;
        fencePreserveRaw = false;
        continue;
      }
      if (/^\s{0,3}```/.test(line)) {
        // 0~3칸 들여쓴 ``` 포함 거절 — CommonMark 는 들여쓴 닫기도 인정하므로
        // 저장 코드에 남으면 가이드 재펜싱·wrapDesignPayload 블록이 조기 종결된다.
        issues.push({
          layer: 'structure',
          path: path(),
          message: `펜스 내부에 또 다른 백틱 펜스 라인이 있습니다(행 ${lineNo}) — 닫기는 \`\`\` 단독 행만 허용됩니다.`,
        });
        continue;
      }
      if (fenceIsComponentCode && PROVENANCE_LINE_RE.test(line)) continue; // provenance strip
      fenceSink?.push(line);
      continue;
    }

    if (TILDE_FENCE_RE.test(line)) {
      issues.push({ layer: 'structure', path: path(), message: `틸드(~~~) 펜스는 지원하지 않습니다(행 ${lineNo}) — 백틱 3개를 사용하세요.` });
      continue;
    }
    if (LONG_FENCE_RE.test(line)) {
      issues.push({ layer: 'structure', path: path(), message: `4개 이상 백틱 펜스는 지원하지 않습니다(행 ${lineNo}) — 백틱 정확히 3개를 사용하세요.` });
      continue;
    }
    const fenceOpen = line.match(FENCE_OPEN_RE);
    if (fenceOpen) {
      inFence = true;
      fenceStartLine = lineNo;
      fenceInfo = fenceOpen[1].toLowerCase();
      fenceIsComponentCode = false;
      fencePreserveRaw = false;
      if (section === 'components' && curComponent) {
        if (curComponent.sub === 'code') {
          curComponent.codeFenceCount += 1;
          if (curComponent.codeFenceCount > 1) {
            issues.push({ layer: 'structure', path: componentPath(), message: '#### Code 에는 코드 펜스를 1개만 둘 수 있습니다.' });
            fenceSink = [];
          } else if (!DESIGN_CODE_LANGS.has(fenceInfo)) {
            issues.push({
              layer: 'structure',
              path: componentPath(),
              message: `#### Code 펜스 언어는 tsx 또는 jsx 여야 합니다(현재: "${fenceInfo || '없음'}").`,
            });
            fenceSink = [];
          } else {
            curComponent.codeLang = fenceInfo as 'tsx' | 'jsx';
            fenceSink = curComponent.codeLines;
            fenceIsComponentCode = true;
          }
        } else if (curComponent.sub === 'usage') {
          curComponent.usageLines.push(line);
          fenceSink = curComponent.usageLines;
        } else if (curComponent.sub === 'variants') {
          curComponent.variantsLines.push(line);
          fenceSink = curComponent.variantsLines;
        } else {
          curComponent.descriptionLines.push(line);
          fenceSink = curComponent.descriptionLines;
        }
        if (!fenceIsComponentCode && fenceSink !== null && fenceSink.length > 0) fencePreserveRaw = true;
        continue;
      }
      if (section === 'resources' && curResource) {
        curResource.bodyLines.push(line);
        fenceSink = curResource.bodyLines;
        fencePreserveRaw = true;
        continue;
      }
      if (section === 'components' || section === 'resources') {
        // H3 아이템 밖 펜스 — 산문과 동일하게 거절 (무경고 overview 누수 차단, 결정성 원칙)
        issues.push({
          layer: 'structure',
          path: `body:${lineNo}`,
          message: `\`## ${section === 'components' ? 'Components' : 'Resources'}\` 아래 코드 펜스는 H3 ${section === 'components' ? '컴포넌트' : '리소스'} 안에만 둘 수 있습니다.`,
        });
        fenceSink = []; // discard
        continue;
      }
      overviewLines.push(line);
      fenceSink = overviewLines;
      fencePreserveRaw = true;
      continue;
    }

    // --- 헤딩 ---
    const h = line.match(HEADING_RE);
    if (h) {
      const level = h[1].length;
      const text = h[2].trim();

      if (level === 2) {
        const lower = text.toLowerCase();
        if (lower === 'components') {
          if (seenComponents) {
            issues.push({ layer: 'structure', path: `body:${lineNo}`, message: '`## Components` 섹션이 중복됩니다.' });
            continue;
          }
          curComponent = flushComponent(curComponent);
          curResource = flushResource(curResource);
          seenComponents = true;
          section = 'components';
          continue;
        }
        if (lower === 'resources') {
          if (seenResources) {
            issues.push({ layer: 'structure', path: `body:${lineNo}`, message: '`## Resources` 섹션이 중복됩니다.' });
            continue;
          }
          curComponent = flushComponent(curComponent);
          curResource = flushResource(curResource);
          seenResources = true;
          section = 'resources';
          continue;
        }
        // 규약 외 H2 → overview 보존 (후속 `## Assets` 하위호환 근거)
        curComponent = flushComponent(curComponent);
        curResource = flushResource(curResource);
        section = 'overview';
        overviewLines.push(line);
        continue;
      }

      if (section === 'components') {
        if (level === 3) {
          curComponent = flushComponent(curComponent);
          curComponent = openComponent(text, lineNo);
          continue;
        }
        if (level === 4 && curComponent) {
          const lower = text.toLowerCase();
          if (lower === 'usage' || lower === 'variants' || lower === 'code') {
            if (curComponent.seenSubs.has(lower)) {
              issues.push({ layer: 'structure', path: componentPath(), message: `#### ${text} 서브섹션이 중복됩니다.` });
              continue;
            }
            curComponent.seenSubs.add(lower);
            curComponent.sub = lower as Subsection;
            continue;
          }
          issues.push({
            layer: 'structure',
            path: componentPath(),
            message: `컴포넌트 안에서 지원하지 않는 서브섹션입니다: "#### ${text}" (Usage/Variants/Code 만 허용).`,
          });
          continue;
        }
        // 컴포넌트 섹션 내 미지 헤딩(H1, H5+, 컴포넌트 밖 H4 등) = 거절
        issues.push({
          layer: 'structure',
          path: curComponent ? componentPath() : `body:${lineNo}`,
          message: `Components 섹션에서 지원하지 않는 헤딩입니다(행 ${lineNo}): "${line.slice(0, 40)}"`,
        });
        continue;
      }

      if (section === 'resources') {
        if (level === 3) {
          curResource = flushResource(curResource);
          curResource = openResource(text, lineNo);
          continue;
        }
        if (level >= 4 && curResource) {
          curResource.bodyLines.push(line); // 리소스 본문 내 H4+ 는 자유 (가이드 렌더 시 demote)
          continue;
        }
        issues.push({
          layer: 'structure',
          path: curResource ? resourcePath() : `body:${lineNo}`,
          message: `Resources 섹션에서 지원하지 않는 헤딩입니다(행 ${lineNo}): "${line.slice(0, 40)}"`,
        });
        continue;
      }

      // overview: H1~H6 원문 보존 (가이드 렌더 시 demote)
      overviewLines.push(line);
      continue;
    }

    // --- 일반 라인 ---
    if (section === 'components' && curComponent) {
      if (curComponent.sub === 'description') curComponent.descriptionLines.push(line);
      else if (curComponent.sub === 'usage') curComponent.usageLines.push(line);
      else if (curComponent.sub === 'variants') curComponent.variantsLines.push(line);
      else if (curComponent.sub === 'code' && line.trim() !== '') {
        issues.push({ layer: 'structure', path: componentPath(), message: '#### Code 에는 코드 펜스 외 산문을 둘 수 없습니다.' });
      }
      continue;
    }
    if (section === 'components') {
      if (line.trim() !== '') {
        issues.push({ layer: 'structure', path: `body:${lineNo}`, message: '`## Components` 아래 산문은 H3 컴포넌트 안에만 둘 수 있습니다.' });
      }
      continue;
    }
    if (section === 'resources' && curResource) {
      curResource.bodyLines.push(line);
      continue;
    }
    if (section === 'resources') {
      if (line.trim() !== '') {
        issues.push({ layer: 'structure', path: `body:${lineNo}`, message: '`## Resources` 아래 산문은 H3 리소스 안에만 둘 수 있습니다.' });
      }
      continue;
    }
    overviewLines.push(line);
  }

  if (inFence) {
    issues.push({
      layer: 'structure',
      path: `body:${fenceStartLine}`,
      message: `행 ${fenceStartLine} 에서 열린 코드 펜스가 닫히지 않았습니다(미종결 펜스 거절).`,
    });
  }
  curComponent = flushComponent(curComponent);
  curResource = flushResource(curResource);

  if (seenComponents && components.length === 0 && issues.every((it) => !it.path.startsWith('components/'))) {
    issues.push({ layer: 'structure', path: 'components', message: '`## Components` 섹션에 H3 컴포넌트가 없습니다.' });
  }

  const structureFailed = issues.some((it) => it.layer === 'structure');
  if (structureFailed) return { ok: false, issues };

  return {
    ok: true,
    issues,
    value: {
      name,
      title,
      description,
      version,
      stack,
      tokens,
      themes,
      overviewMd: overviewLines.join('\n').trim(),
      components,
      resources,
    },
  };
}

/* ------------------------------------------------------------------ */
/* 펜스 분리 헬퍼 — 검증(designValidation)이 산문↔코드 계층 분리에 재사용     */
/* ------------------------------------------------------------------ */

export interface FenceSplit {
  prose: string;
  fenced: string[];
}

/**
 * 마크다운을 펜스 밖 산문과 펜스 내부 코드로 분리한다.
 * 파서와 동일한 펜스 화이트리스트 상태기계를 사용(경계 판정 단일화).
 * (파서를 통과한 문자열이 입력 전제 — 미종결·틸드·4+백틱은 이미 거절됨)
 */
export function splitFences(md: string): FenceSplit {
  const proseLines: string[] = [];
  const fenced: string[] = [];
  let cur: string[] | null = null;
  for (const line of md.split('\n')) {
    if (cur !== null) {
      if (FENCE_CLOSE_RE.test(line)) {
        fenced.push(cur.join('\n'));
        cur = null;
        continue;
      }
      cur.push(line);
      continue;
    }
    if (FENCE_OPEN_RE.test(line)) {
      cur = [];
      continue;
    }
    proseLines.push(line);
  }
  if (cur !== null) fenced.push(cur.join('\n'));
  return { prose: proseLines.join('\n'), fenced };
}
